import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../term-tests/substitute-shared/state.js',import.meta.url),'utf8');
const epoch='11111111-1111-4111-8111-111111111111',run='22222222-2222-4222-8222-222222222222';
function storage(){const map=new Map();return {get length(){return map.size;},key:i=>[...map.keys()][i],getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};}
async function setup(slug){const listeners={},events=[];const c=vm.createContext({sessionStorage:storage(),localStorage:storage(),AbortController,setTimeout,clearTimeout,Event,crypto:{randomUUID:()=>run},history:{replaceState(){}},location:{href:'https://fixture.test/'},fetch:async()=>({ok:true,json:async()=>({testSlug:slug,historyEpoch:epoch,stateVersion:2,maintenance:false})}),window:{addEventListener:(k,f)=>listeners[k]=f,dispatchEvent:e=>events.push(e.type)}});vm.runInContext(source,c);const api=c.window.SUBSTITUTE_STATE;await api.initialize({slug},{API_BASE_URL:'https://fixture.test/gateway'});api.bind({classCode:'DEMO',studentRef:'fictional-A',clientRunId:run});return {api,c,listeners,events};}
for(const slug of ['substitute-test-1-k56','substitute-test-2-k56','substitute-test-1-k67','substitute-test-2-k67']){
test(slug+': đúng toàn bộ định danh, token và epoch; điểm 0 thật vẫn hợp lệ',async()=>{const {api}=await setup(slug);const saved=api.stamp({testGrades:{listening:{correct:0}}});assert.equal(api.accept(saved),true);assert.equal(api.accept({...saved,_substitute:{...saved._substitute,historyEpoch:run}}),false);api.bind({classCode:'DEMO',studentRef:'fictional-B',clientRunId:run});assert.equal(api.accept(saved),false);api.bind({classCode:'DEMO',studentRef:'fictional-A',clientRunId:run,attemptToken:epoch});assert.equal(api.accept(saved),false);});
test(slug+': reset xóa tất cả khóa cũ, giữ bài khác, broadcast và chặn ghi/poll',async()=>{const {api,c,events}=await setup(slug);const controller=new AbortController();api.track(controller);for(const s of [c.sessionStorage,c.localStorage]){for(const p of ['izone-test:','izone-test-ui:','izone-test-annotations:'])s.setItem(p+slug+':IC2264:old','fake');s.setItem('izone-test:unrelated:old','fake');}api.clear(slug);for(const s of [c.sessionStorage,c.localStorage]){assert.equal(s.getItem('izone-test:'+slug+':IC2264:old'),null);assert.equal(s.getItem('izone-test:unrelated:old'),'fake');}assert.ok(c.localStorage.getItem('izone-demo-reset:'+slug+':RETAKE-LOBBY:server-grade'));assert.equal(controller.signal.aborted,true);assert.ok(events.includes('substitute:stopped'));assert.throws(()=>api.payload({}),/hết hiệu lực/);assert.throws(()=>api.stamp({}),/reset/);});
test(slug+': reload chỉ tìm lobby trong session hiện hành, không nhận localStorage của học viên trước',async()=>{const {api,c}=await setup(slug);const src=fs.readFileSync(new URL('../term-tests/'+slug+'-computer-based/bootstrap.js',import.meta.url),'utf8');const start=src.indexOf('  function readState()'),end=src.indexOf('  function readLegacyUiState()',start);c.window.SUBSTITUTE_STATE=api;c.storageKey='fixture-lobby';c.localStorage.setItem(c.storageKey,JSON.stringify(api.stamp({studentRef:'fictional-A',classCode:'DEMO',clientRunId:run})));vm.runInContext(src.slice(start,end),c);assert.equal(JSON.stringify(vm.runInContext('readState()',c)),'{}');});
}
test('Sub 2 K67: phiên đề là một phần định danh, không khôi phục nháp khác phiên',async()=>{
 const {api}=await setup('substitute-test-2-k67');const legacy=api.stamp({});
 api.bind({classCode:'DEMO',studentRef:'fictional-A',clientRunId:run,examVersion:'substitute-k67-test2-two-task-20261007-v1'});
 assert.equal(api.accept(legacy),false);const current=api.stamp({});assert.equal(api.accept(current),true);
 assert.equal(api.payload({}).examVersion,'substitute-k67-test2-two-task-20261007-v1');
});
