/* Đánh máy theo Reading PDF do người dùng cung cấp; giữ nguyên nội dung đề. */
window.K56_TEST2_PASSAGES = [
  {
    title: 'Seaweeds of New Zealand',
    paragraphs: [
      `Seaweed is a particularly wholesome food, which absorbs and concentrates traces of a wide variety of minerals necessary to the body’s health. Many elements may occur in seaweed – aluminium, barium, calcium, chlorine, copper, iodine and iron, to name but a few – traces normally produced by erosion and carried to the seaweed beds by river and sea currents. Seaweeds are also rich in vitamins; indeed, Inuits obtain a high proportion of their bodily requirements of vitamin C from the seaweeds they eat. The health benefits of seaweed have long been recognised. For instance, there is a remarkably low incidence of goitre among the Japanese, and also among New Zealand’s indigenous Maori people, who have always eaten seaweeds, and this may well be attributed to the high iodine content of this food. Research into historical Maori eating customs shows that jellies were made using seaweeds, nuts, fuchsia and tutu berries, cape gooseberries, and many other fruits both native to New Zealand and sown there from seeds brought by settlers and explorers. As with any plant life, some seaweeds are more palatable than others, but in a survival situation, most seaweeds could be chewed to provide a certain sustenance.`,
      `New Zealand lays claim to approximately 700 species of seaweed, some of which have no representation outside that country. Of several species grown worldwide, New Zealand also has a particularly large share. For example, it is estimated that New Zealand has some 30 species of Gigartina, a close relative of carrageen or Irish moss. These are often referred to as the New Zealand carrageens. The substance called agar which can be extracted from these species gives them great commercial application in the production of seameal, from which seameal custard (a food product) is made, and in the canning, paint and leather industries. Agar is also used in the manufacture of cough mixtures, cosmetics, confectionery and toothpastes. In fact, during World War II, New Zealand Gigartina were sent to Australia to be used in toothpaste.`,
      `New Zealand has many of the commercially profitable red seaweeds, several species of which are a source of agar (Pterocladia, Gelidium, Chondrus, Gigartina). Despite this, these seaweeds were not much utilised until several decades ago. Although distribution of the Gigartina is confined to certain areas according to species, it is only on the east coast of the North Island that its occurrence is rare. And even then, the east coast, and the area around Hokianga, have a considerable supply of the two species of Pterocladia from which agar is also made. New Zealand used to import the Northern Hemisphere Irish moss (Chondrus crispus) from England and ready-made agar from Japan.`,
      `Seaweeds are divided into three classes determined by colour – red, brown and green – and each tends to live in a specific position. However, except for the unmistakable sea lettuce (Ulva), few are totally one colour; and especially when dry, some species can change colour significantly – a brown one may turn quite black, or a red one appear black, brown, pink or purple. Identification is nevertheless facilitated by the fact that the factors which determine where a seaweed will grow are quite precise, and they tend therefore to occur in very well-defined zones. Although there are exceptions, the green seaweeds are mainly shallow-water algae; the browns belong to the medium depths; and the reds are plants of the deeper water, furthest from the shore. Those shallow-water species able to resist long periods of exposure to sun and air are usually found on the upper shore, while those less able to withstand such exposure occur nearer to, or below, the low-water mark. Radiation from the sun, the temperature level, and the length of time immersed also play a part in the zoning of seaweeds. Flat rock surfaces near mid-level tides are the most usual habitat of sea-bombs, Venus’ necklace, and most brown seaweeds. This is also the home of the purple laver or Maori karengo, which looks rather like a reddish-purple lettuce. Deep-water rocks on open coasts, exposed only at very low tide, are usually the site of bull-kelp, strapweeds and similar tough specimens. Kelp, or bladder kelp, has stems that rise to the surface from massive bases or ‘holdfasts’, the leafy branches and long ribbons of leaves surging with the swells beyond the line of shallow coastal breakers or covering vast areas of calmer coastal water.`,
      `Propagation of seaweeds occurs by seed-like spores, or by fertilisation of egg cells. None have roots in the usual sense; few have leaves; and none have flowers, fruits or seeds. The plants absorb their nourishment through their leafy fronds when they are surrounded by water; the holdfast of seaweeds is purely an attaching organ, not an absorbing one.`,
      `Some of the large seaweeds stay on the surface of the water by means of air-filled floats; others, such as bull-kelp, have large cells filled with air. Some which spend a good part of their time exposed to the air, often reduce dehydration either by having swollen stems that contain water, or they may (like Venus’ necklace) have swollen nodules, or they may have a distinctive shape like a sea-bomb. Others, like the sea cactus, are filled with a slimy fluid or have a coating of mucilage on the surface. In some of the larger kelps, this coating is not only to keep the plant moist, but also to protect it from the violent action of waves.`
    ]
  },
  {
    title: 'TWO WINGS AND A TOOLKIT',
    subtitle: 'A research team at Oxford University discover the remarkable toolmaking skills of New Caledonian crows',
    unlettered: true,
    paragraphs: [
      `Betty and her mate Abel are captive crows in the care of Alex Kacelnik, an expert in animal behaviour at Oxford University. They belong to a forest-dwelling species of bird (Corvus moneduloides) confined to two islands in the South Pacific. New Caledonian crows are tenacious predators, and the only birds that habitually use a wide selection of self-made tools to find food.`,
      `One of the wild crows’ cleverest tools is the crochet hook, made by detaching a side twig from a larger one, leaving enough of the larger twig to shape into a hook. Equally cunning is a tool crafted from the barbed vine-leaf, which consists of a central rib with paired leaflets each with a rose-like thorn at its base. They strip out a piece of this rib, removing the leaflets and all but one thorn at the top, which remains as a ready-made hook to prise out insects from awkward cracks.`,
      `The crows also make an ingenious tool called a pandanus probe from pandanus tree leaves. The tool has a broad base, sharp tip, a row of tiny hooks along one edge, and a tapered shape created by the crow nipping and tearing to form a progression of three or four steps along the other edge of the leaf. What makes this tool special is that they manufacture it to a standard design, as if following a set of instructions. Although it is rare to catch a crow in the act of clipping out a pandanus probe, we do have ample proof of their workmanship: the discarded leaves from which the tools are cut. The remarkable thing that these ‘counterpart’ leaves tell us is that crows consistently produce the same design every time, with no in-between or trial versions. It’s left the researchers wondering whether, like people, they envisage the tool before they start and perform the actions they know are needed to make it. Research has revealed that genetics plays a part in the less sophisticated toolmaking skills of finches in the Galápagos islands. No one knows if that’s also the case for New Caledonian crows, but it’s highly unlikely that their toolmaking skills are hardwired into the brain. ‘The picture so far points to a combination of cultural transmission – from parent birds to their young – and individual resourcefulness,’ says Kacelnik.`,
      `In a test at Oxford, Kacelnik’s team offered Betty and Abel an original challenge – food in a bucket at the bottom of a ‘well’. The only way to get the food was to hook the bucket out by its handle. Given a choice of tools – a straight length of wire and one with a hooked end – the birds immediately picked the hook, showing that they did indeed understand the functional properties of the tool.`,
      `But do they also have the foresight and creativity to plan the construction of their tools? It appears they do. In one bucket-in-the-well test, Abel carried off the hook, leaving Betty with nothing but the straight wire. ‘What happened next was absolutely amazing,’ says Kacelnik. She wedged the tip of the wire into a crack in a plastic dish and pulled the other end to fashion her own hook. Wild crows don’t have access to pliable, bendable material that retains its shape, and Betty’s only similar experience was a brief encounter with some pipe cleaners a year earlier. In nine out of ten further tests, she again made hooks and retrieved the bucket.`,
      `The question of what’s going on in a crow’s mind will take time and a lot more experiments to answer, but there could be a lesson in it for understanding our own evolution. Maybe our ancestors, who suddenly began to create symmetrical tools with carefully worked edges some 1.5 million years ago, didn’t actually have the sophisticated mental abilities with which we credit them. Closer scrutiny of the brains of New Caledonian crows might provide a few pointers to the special attributes they would have needed. ‘If we’re lucky we may find specific developments in the brain that set these animals apart,’ says Kacelnik.`,
      `One of these might be a very strong degree of laterality – the specialisation of one side of the brain to perform specific tasks. In people, the left side of the brain controls the processing of complex sequential tasks, and also language and speech. One of the consequences of this is thought to be right-handedness. Interestingly, biologists have noticed that most pandanus probes are cut from the left side of the leaf, meaning that the birds clip them with the right side of their beaks – the crow equivalent of right-handedness. The team thinks this reflects the fact that the left side of the crow’s brain is specialised to handle the sequential processing required to make complex tools.`,
      `Under what conditions might this extraordinary talent have emerged in these two species? They are both social creatures, and wide-ranging in their feeding habits. These factors were probably important but, ironically, it may have been their shortcomings that triggered the evolution of toolmaking. Maybe the ancestors of crows and humans found themselves in a position where they couldn’t make the physical adaptations required for survival – so they had to change their behaviour instead. The stage was then set for the evolution of those rare cognitive skills that produce sophisticated tools. New Caledonian crows may tell us what those crucial skills are.`
    ]
  },
  {
    title: 'The meaning and power of smell',
    subtitle: 'The sense of smell, or olfaction, is powerful. Odours affect us on a physical, psychological and social level. For the most part, however, we breathe in the aromas which surround us without being consciously aware of their importance to us. It is only when the faculty of smell is impaired for some reason that we begin to realise the essential role the sense of smell plays in our sense of well-being',
    paragraphs: [
      `A survey conducted by Anthony Synnott at Montreal’s Concordia University asked participants to comment on how important smell was to them in their lives. It became apparent that smell can evoke strong emotional responses. A scent associated with a good experience can bring a rush of joy, while a foul odour or one associated with a bad memory may make us grimace with disgust. Respondents to the survey noted that many of their olfactory likes and dislikes were based on emotional associations. Such associations can be powerful enough so that odours that we would generally label unpleasant become agreeable, and those that we would generally consider fragrant become disagreeable for particular individuals. The perception of smell, therefore, consists not only of the sensation of the odours themselves, but of the experiences and emotions associated with them.`,
      `Odours are also essential cues in social bonding. One respondent to the survey believed that there is no true emotional bonding without touching and smelling a loved one. In fact, infants recognise the odours of their mothers soon after birth and adults can often identify their children or spouses by scent. In one well-known test, women and men were able to distinguish by smell alone clothing worn by their marriage partners from similar clothing worn by other people. Most of the subjects would probably never have given much thought to odour as a cue for identifying family members before being involved in the test, but as the experiment revealed, even when not consciously considered, smells register.`,
      `In spite of its importance to our emotional and sensory lives, smell is probably the most undervalued sense in many cultures. The reason often given for the low regard in which smell is held is that, in comparison with its importance among animals, the human sense of smell is feeble and undeveloped. While it is true that the olfactory powers of humans are nothing like as fine as those possessed by certain animals, they are still remarkably acute. Our noses are able to recognise thousands of smells, and to perceive odours which are present only in extremely small quantities.`,
      `Smell, however, is a highly elusive phenomenon. Odours, unlike colours, for instance, cannot be named in many languages because the specific vocabulary simply doesn’t exist. ‘It smells like . . . ,’ we have to say when describing an odour, struggling to express our olfactory experience. Nor can odours be recorded: there is no effective way to either capture or store them over time. In the realm of olfaction, we must make do with descriptions and recollections. This has implications for olfactory research.`,
      `Most of the research on smell undertaken to date has been of a physical scientific nature. Significant advances have been made in the understanding of the biological and chemical nature of olfaction, but many fundamental questions have yet to be answered. Researchers have still to decide whether smell is one sense or two – one responding to odours proper and the other registering odourless chemicals in the air. Other unanswered questions are whether the nose is the only part of the body affected by odours, and how smells can be measured objectively given the non-physical components. Questions like these mean that interest in the psychology of smell is inevitably set to play an increasingly important role for researchers.`,
      `However, smell is not simply a biological and psychological phenomenon. Smell is cultural, hence it is a social and historical phenomenon. Odours are invested with cultural values: smells that are considered to be offensive in some cultures may be perfectly acceptable in others. Therefore, our sense of smell is a means of, and model for, interacting with the world. Different smells can provide us with intimate and emotionally charged experiences and the value that we attach to these experiences is interiorised by the members of society in a deeply personal way. Importantly, our commonly held feelings about smells can help distinguish us from other cultures. The study of the cultural history of smell is, therefore, in a very real sense, an investigation into the essence of human culture.`
    ]
  }
];
