"use strict";

// Dữ liệu bài làm giả định dựng các màn minh họa. Chuyển bước không gửi bài hay gọi AI.
const prompt = "Governments should spend more money on public transport than on building new roads. To what extent do you agree or disagree?";
const stance = "Ưu tiên giao thông công cộng ở đô thị đông dân đã có đường; vẫn đầu tư đường cần thiết ở nơi thiếu kết nối cơ bản.";
const body = "In crowded cities with an established road network, I would prioritise improvements to public transport because they can make commuting more dependable and affordable. More frequent and reliable bus services reduce waiting times and help commuters predict how long their journeys will take. They can then plan when to leave home, lowering the risk of arriving late for work. Where fares are reasonable and routes cover their journeys, commuters may also use buses instead of private vehicles. Spending less on fuel and parking can leave them with more money for essential needs. In this context, improving services on existing roads deserves priority over simply adding more roads without addressing how people travel.";
const essayParagraphs = [
  "Governments need to decide how to divide transport budgets between public services and new roads. I believe public transport deserves priority in crowded cities with established road networks, while roads remain essential where basic connections are missing.",
  "In crowded cities, better public transport can make commuting more dependable and affordable. More frequent and reliable bus services reduce waiting times and allow people to predict the length of their journeys. They can therefore choose when to leave home. Commuters will never be late for work if the city invests in buses. Services with reasonable fares and suitable routes may also provide an alternative to private vehicles. Spending less on fuel and parking could leave commuters with more money for essential needs. These benefits support improving services on existing roads rather than simply adding more roads without considering how people travel.",
  "However, some areas still need basic road connections. A road linking an isolated community to a town can allow residents to reach medical services that were previously difficult to access. Producers may also use the connection to transport goods to markets and meet buyers outside their local area. This can create more opportunities to sell products and earn an income. In such places, new road connections should take priority because spending more on public transport alone cannot replace the basic infrastructure needed for travel. The decision should therefore depend on the needs of the area.",
  "In conclusion, governments should stop spending money on new roads and invest all transport budgets in public transport."
];
const topics = [
  ["Giao thông", prompt],
  ["Giáo dục", "Schools should replace some homework with practical activities outside the classroom. To what extent do you agree or disagree?"],
  ["Công việc", "Employers should allow employees to work from home whenever their jobs can be done remotely. To what extent do you agree or disagree?"],
  ["Công nghệ", "Children under the age of sixteen should not be allowed to own smartphones. To what extent do you agree or disagree?"],
  ["Quảng cáo", "Advertisements aimed at children should be banned. To what extent do you agree or disagree?"],
  ["Không gian đô thị", "Cities should use more land for public parks rather than for shopping centres. To what extent do you agree or disagree?"]
];
const chapters = [
  { title: "Trên lớp", detail: "Nghĩ ý · Dàn ý · Viết đoạn" },
  { title: "Brainstorm ở nhà", detail: "Sáu topic · AI · Trợ giúp" },
  { title: "Viết full bài", detail: "Hoàn thành · Nộp bài" },
  { title: "Điểm và chữa bài", detail: "Tiến bộ · TR/CC · Từng câu" }
];
const escape = value => String(value).replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const field = (label, value, empty = false) => `<div class="field"><span class="field-label">${escape(label)}</span><div class="field-value${empty ? " empty" : ""}">${escape(value)}</div></div>`;
const heading = (title, timer = "") => `<div class="screen-header"><h3>${escape(title)}</h3>${timer ? `<span class="clock">${escape(timer)}</span>` : ""}</div>`;
const question = (text = prompt) => `<p class="topic">${escape(text)}</p>`;
const action = (label, type = "primary") => `<div class="actions"><button class="button ${type}" data-action="next" type="button">${escape(label)}</button></div>`;
const dialogue = messages => `<div class="dialogue">${messages.map(([role, text]) => `<div class="message ${role === "Giảng viên" ? "teacher" : role.startsWith("Học viên") ? "student" : "ai"}"><span class="speaker">${escape(role)}</span><p>${escape(text)}</p></div>`).join("")}</div>`;
const chain = (a, x, b) => `<div class="chain"><span class="chain-key">A</span><p>${escape(a)}</p><span class="chain-key">X</span><p>${escape(x)}</p><span class="chain-key">B</span><p>${escape(b)}</p></div>`;
const htmlEssay = () => `<div class="essay essay-box" tabindex="0" aria-label="Bài full minh họa">${essayParagraphs.map(p => `<p>${escape(p)}</p>`).join("")}</div>`;
const fullOutline = () => `${heading("Dàn ý toàn bài của tôi")}<span class="status good">Đã đủ cấu trúc bài</span><section class="outline-section"><h4>Mở bài · Quan điểm</h4><p>${escape(stance)}</p></section><section class="outline-section"><h4>Thân bài 1 · Di chuyển đáng tin cậy và tiết kiệm hơn</h4><p class="chain-label">Ý 1 · Chủ động thời gian</p>${chain("Xe buýt thường xuyên và đáng tin cậy hơn.","Chờ ít, dự tính thời gian đi, chọn giờ ra khỏi nhà.","Giảm nguy cơ đến chỗ làm muộn.")}<p class="chain-label">Ý 2 · Giảm chi phí</p>${chain("Giá vé hợp lý, có tuyến phù hợp.","Dùng xe buýt thay xe cá nhân; giảm chi phí nhiên liệu và đỗ xe nếu tổng chi thấp hơn.","Giữ lại nhiều thu nhập hơn cho nhu cầu thiết yếu.")}<p class="micro-note">Liên hệ đề: ở đô thị đã có đường, ưu tiên làm dịch vụ trên mạng lưới ấy phù hợp với người đi làm.</p></section><section class="outline-section"><h4>Thân bài 2 · Nơi thiếu kết nối vẫn cần đầu tư đường</h4>${chain("Có đường nối vùng cô lập tới thị trấn.","Người dân di chuyển tới cơ sở y tế.","Tiếp cận khám chữa bệnh thuận tiện hơn.")}${chain("Đường nối nơi sản xuất với nơi bán hàng.","Vận chuyển sản phẩm, tiếp cận thêm người mua.","Có thêm cơ hội bán hàng và tạo thu nhập.")}</section><section class="outline-section"><h4>Kết bài</h4><p>Khẳng định ưu tiên theo bối cảnh, giữ đúng giới hạn của quan điểm mở bài.</p></section>`;

// Mỗi bước có màn học viên, vai trò của ba bên và sản phẩm cần đạt.
const steps = [];
function add(chapter, title, intro, screen, student, teacher, ai, outcome) { steps.push({chapter,title,intro,screen,student,teacher,ai,outcome}); }
add(0,"Bắt đầu buổi Writing","Học viên biết ngay mình sẽ hoàn thành gì trên lớp và ở nhà.",() => `${heading("Buổi Writing · Task 2")}<p class="large-statement">Chọn ý mình hiểu rõ.<br>Phát triển đủ chất lượng.<br>Viết kịp trong phòng thi.</p><dl class="definition-list"><div><dt>Trên lớp</dt><dd>Dàn ý cả bài, luyện gọi ra từ/cụm từ, viết ít nhất một thân bài hoàn chỉnh.</dd></div><div><dt>Ở nhà</dt><dd>Brainstorm sáu topic và viết một bài full.</dd></div><div><dt>Kết quả</dt><dd>Điểm như bài Test, theo dõi tiến bộ; chữa TR, CC và từng câu.</dd></div></dl>${action("Bắt đầu đọc đề")}`,"Đọc mục tiêu và chuẩn bị tự làm.","Giải thích mục tiêu chất lượng đi cùng tốc độ.","Hỗ trợ sau khi học viên có phần tự làm.","Học viên hiểu toàn bộ đường học trước khi bắt đầu.");
add(0,"Đọc đề và xác định nhiệm vụ","Trước khi nghĩ ý, học viên làm rõ đề đang yêu cầu trả lời điều gì.",() => `${heading("Đọc đề")}${question()}${field("Đề yêu cầu làm gì?","Nêu mức độ đồng ý với việc ưu tiên ngân sách cho giao thông công cộng hơn đường mới.")}${field("Trọng tâm bàn luận","So sánh lựa chọn đầu tư, không chỉ liệt kê ưu điểm xe buýt.")}${action("Bắt đầu nghĩ ý")}`,"Tự xác định yêu cầu, trọng tâm và bối cảnh.","Phát hiện người đang bỏ sót yêu cầu so sánh.","Chưa đưa sẵn ngân hàng ý.","Có cách hiểu đề trước khi chọn nội dung.");
add(0,"Brainstorm lần đầu","Lượt tự nghĩ giúp giảng viên nhìn được chất lượng và tốc độ ban đầu.",() => `${heading("Tôi chọn hướng trả lời","Lượt tự nghĩ · 02:00")}${field("Hướng trả lời",stance)}${field("Ý đang nghĩ","Giao thông công cộng giúp nền kinh tế cạnh tranh hơn.")}${field("Vì sao?","Em chưa giải thích rõ đường từ dịch vụ xe buýt tới cả nền kinh tế.")}${action("Gửi ý để nhận phản hồi")}`,"Tự ghi ý và điều mình giải thích được.","Xem ý thật của học viên thay vì đưa bộ ý chuẩn bị sẵn.","Chỉ nhận xét phần học viên vừa ghi.","Giữ phiên bản tự nghĩ để không nhầm với ý sau hỗ trợ.");
add(0,"AI hỏi đúng chỗ chưa rõ","Phản hồi không bắt học viên đổi sang ý của AI.",() => `${heading("Làm rõ ý ban đầu")}${field("Ý của tôi","Giao thông công cộng giúp nền kinh tế cạnh tranh hơn.")}${dialogue([["AI","Bạn chọn một nhóm người trong bức tranh đó được không? Dịch vụ thay đổi điều gì trong việc thường ngày của họ?"],["Học viên","Người đi làm có thể đến công ty đúng giờ hơn."]])}${action("Trao đổi với giảng viên")}`,"Trả lời câu hỏi và tự thu hẹp kết quả.","Theo dõi ai vẫn mắc hoặc không đồng ý với feedback.","Ưu tiên một điểm cần làm rõ mỗi lượt.","Ý bắt đầu có đối tượng và kết quả cụ thể.");
add(0,"Giảng viên kiểm độ quen thuộc của ý","Cùng một ý có thể dễ với người này, khó với người khác.",() => `${heading("Giữ ý hay đổi hướng?")}<div class="two-column"><div class="comparison"><span class="status good">Học viên A · Quen thuộc</span>${dialogue([["Học viên A","Em hiểu chuỗi về chi phí vận hành vì từng làm trong doanh nghiệp. Em có thể giải thích và viết được ngay."],["Giảng viên","Mình giữ hướng ấy nếu đúng đề; em làm rõ đối tượng và giới hạn kết luận."]])}</div><div class="comparison"><span class="status attention">Học viên B · Còn xa lạ</span>${dialogue([["Học viên B","Em phải đoán nhiều bước, khi viết cũng chưa gọi tên được."],["Giảng viên","Mình chọn tác động gần trải nghiệm hơn, như thời gian đi làm. Em vẫn phải giải thích đủ rõ và tự viết được nhanh."]])}</div></div>${action("Xem cách chốt điểm cuối")}`,"Thử tự giải thích và chuyển ý sang tiếng Anh.","Đánh giá độ khó theo chính người học, không theo tên ý.","Không mặc định mọi ý vĩ mô đều phải bỏ.","Chọn ý đủ chất lượng và triển khai được kịp khi thi.");
add(0,"Khi cần: thấy chuỗi ý bị lệch","Hoạt động này dùng khi giới thiệu thao tác hoặc lớp còn mắc; không có ở mọi buổi.",() => `${heading("Vì sao cần biết đích?")}<span class="status attention">Hoạt động bổ sung</span>${field("Thông điệp đoạn","Dịch vụ xe buýt tốt hơn có thể đem lại lợi ích thiết thực cho người đi làm.")}${field("Chuỗi chưa được chốt đích","Xe buýt tốt → nhiều người dùng → doanh nghiệp thêm doanh thu → mua thêm xe → người đi làm bớt áp lực thời gian.")}${dialogue([["Giảng viên","Đoạn nào đã giải thích vì sao người đi làm bớt áp lực thời gian?"],["Học viên","Em đang kể chuyện doanh nghiệp, chưa nối tới lợi ích của người đi làm."]])}${action("Chốt đích trước")}`,"So sánh và đánh dấu chỗ kết quả xuất hiện đột ngột.","Cho thấy lý do của thao tác bằng một ví dụ cụ thể.","Không hiện chuỗi đúng trước khi học viên thử.","Học viên hiểu lỗi, không chỉ nhớ công thức.");
add(0,"Chốt B rồi chọn đường đi","Chuẩn bị B → A → X; khi viết, kể A → X → B.",() => `${heading("Đích rõ giúp chọn bước giữa")}${chain("Xe buýt thường xuyên và đáng tin cậy hơn.","Chờ ít hơn, dự tính thời gian đi và chọn giờ xuất phát.","Giảm nguy cơ đến chỗ làm muộn.")}${dialogue([["Giảng viên","Bây giờ bước giữa có phục vụ đúng kết quả em muốn chứng minh không?"],["Học viên","Có. Em làm B trước để chọn đường, nhưng khi viết vẫn kể từ A qua X đến B."]])}${action("Lập khung toàn bài")}`,"Tự xác định kết quả cụ thể muốn chứng minh.","Kiểm cơ chế, không coi đủ ba ô là lập luận đã tốt.","Gợi đúng phần thiếu nếu đường nối còn đứt.","Có một chuỗi rõ để áp dụng vào các ý của cả bài.");
add(0,"Lập khung cho cả bài","Dàn ý cần đủ mở bài, cả hai thân bài và kết bài ngay trên lớp.",() => `${heading("Khung bài của tôi")}${field("Mở bài · Quan điểm",stance)}${field("Thân bài 1 · Thông điệp","Ưu tiên giao thông công cộng ở đô thị đã có đường: đi làm đáng tin cậy và tiết kiệm hơn.")}${field("Thân bài 2 · Thông điệp","Đầu tư đường vẫn cần thiết ở nơi thiếu kết nối cơ bản.")}${field("Kết bài","Khẳng định ưu tiên theo bối cảnh; không thêm ý mới.")}${action("Làm rõ từng ý hỗ trợ")}`,"Chọn thông điệp và ý hỗ trợ cho cả hai thân bài.","Kiểm hai đoạn có cùng trả lời đề và giữ quan điểm nhất quán.","Nhận xét ý trùng hoặc phạm vi bị bỏ sót.","Không dừng phần trên lớp ở một chuỗi ý riêng lẻ.");
add(0,"Gọi tên B thật cụ thể","Kết quả phải nói rõ lợi cho ai và ở mặt nào.",() => `${heading("Thân bài 1 · Ý hỗ trợ 1")}${field("B ban đầu","Người đi làm có lợi hơn.")}${dialogue([["AI","Bạn muốn nói lợi về thời gian, chi phí hay một thay đổi khác? Chọn một kết quả cho ý này."],["Học viên","Em chọn giảm nguy cơ đến chỗ làm muộn."]])}${field("B sau khi làm rõ","Giảm nguy cơ đến chỗ làm muộn.")}${action("Xác định A")}`,"Tự gọi tên điểm cuối.","Gỡ những tên gọi mơ hồ như tốt hơn, tiện hơn.","Hỏi để học viên chọn, không điền hộ ô B.","B đã cụ thể và khớp thông điệp đoạn.");
add(0,"Xác định A dẫn tới kết quả ấy","Điểm đầu phải là thay đổi có thể dẫn đến B đã chọn.",() => `${heading("Khóa đầu và đích")}${field("B · Kết quả","Giảm nguy cơ đến chỗ làm muộn.")}${field("A · Thay đổi ban đầu","Dịch vụ xe buýt thường xuyên và đáng tin cậy hơn.")}${field("X · Còn cần giải thích","Điều gì xảy ra giữa thay đổi dịch vụ và việc đến đúng giờ?",true)}${action("Viết bước giữa")}`,"Giữ A và B cùng một hướng chứng minh.","Kiểm giả định cần thiết của chuỗi.","Chưa viết sẵn bước giữa.","Có đầu và đích để xây cơ chế.");
add(0,"Viết X lần đầu","Một bước giữa nói lại A chưa giải thích được kết quả.",() => `${heading("Thử nối A tới B")}${chain("Xe buýt thường xuyên và đáng tin cậy hơn.","Dịch vụ xe buýt tốt hơn.","Giảm nguy cơ đến chỗ làm muộn.")}${action("Nhận phản hồi về đường nối")}`,"Tự viết X thay vì chép chuỗi có sẵn.","Nhận ra học viên đang lặp ý hay thiếu cơ chế.","Đọc đúng chuỗi vừa làm.","Lộ điểm mắc để phản hồi trúng chỗ.");
add(0,"Sửa X sau câu hỏi","Học viên giải thích thay đổi cụ thể, không chỉ thêm từ nối.",() => `${heading("Tự sửa cơ chế")}${dialogue([["AI","X đang nói lại A. Người đi làm thay đổi việc chờ xe, dự tính hành trình hoặc chọn giờ ra khỏi nhà như thế nào?"],["Học viên","Họ chờ ít hơn và dự tính thời gian đi, nên chọn giờ ra khỏi nhà hợp lý."]])}${chain("Xe buýt thường xuyên, đáng tin cậy hơn.","Chờ ít hơn → dự tính hành trình → chủ động giờ xuất phát.","Giảm nguy cơ đến chỗ làm muộn.")}${action("Hoàn thiện các ý còn lại")}`,"Tự sửa và giải thích được đường nối.","Can thiệp nếu học viên chỉ thay từ sau nhiều lượt.","Hỏi đúng phần cơ chế còn thiếu.","Chuỗi đã có cơ chế; học viên tiếp tục các ý khác.");
add(0,"Hoàn thành dàn ý toàn bài","Người xem thấy sản phẩm cả bài, không chỉ một ý đã được chữa.",fullOutline,"Tự làm đủ các ý và hướng kết bài.","Nhìn được dàn ý toàn bài của từng người; kiểm độ khớp đề và khả năng viết.","Phản hồi bước đầu ở các ô còn mắc.","Hoàn thành full dàn ý ngay trong lớp.");
add(0,"Trong lúc giảng viên chữa một người","Cả lớp có việc tiếp theo; không nghe tám lượt chữa nối tiếp.",() => `${heading("Một thời điểm trong lớp 8 người")}<p>Giảng viên trao đổi với học viên 1 khoảng 3 phút. Những người khác tiếp tục trên bài riêng.</p><div class="table-wrap"><table><thead><tr><th>Học viên</th><th>Điểm đang mắc</th><th>Việc đang làm</th></tr></thead><tbody><tr><td>1</td><td>Ý rộng, chưa rõ B</td><td>Đối thoại với giảng viên, tự ghi lại chuỗi.</td></tr><tr><td>2</td><td>X lặp A</td><td>Trả lời câu hỏi AI, bổ sung cơ chế.</td></tr><tr><td>3</td><td>Chờ feedback</td><td>Tự đọc và đánh dấu bước chưa giải thích được.</td></tr><tr><td>4</td><td>Chưa có ý</td><td>Nhận câu hỏi Trợ giúp, tự ghi ý.</td></tr><tr><td>5</td><td>Một chuỗi đã rõ</td><td>Hoàn tất các ý còn lại trong dàn ý toàn bài.</td></tr><tr><td>6</td><td>Không đồng ý với AI</td><td>Ghi lý do, nhờ giảng viên xem; làm phần khác.</td></tr><tr><td>7</td><td>B mơ hồ</td><td>Gọi tên lợi ích cụ thể rồi tự sửa.</td></tr><tr><td>8</td><td>Dàn ý đã đủ</td><td>Chuẩn bị ngôn ngữ hoặc bắt đầu viết thân bài.</td></tr></tbody></table></div>${action("Chuyển sang luyện từ vựng")}`,"Tiếp tục ở đúng phần mình còn thiếu.","Chọn ca theo vấn đề; dừng ngắn khi nhiều người mắc cùng lỗi.","Gánh phản hồi bước đầu để lớp tiếp tục tự làm.","Sự can thiệp cá nhân không làm cả lớp ngồi chờ.");
add(0,"Huy động từ vựng từ dàn ý","Giữ khung câu, bỏ từ/cụm từ quan trọng để học viên tự gọi ra.",() => `${heading("Điền ngôn ngữ giữ ý chính","Lượt đầu · 01:30")}${chain("Xe buýt thường xuyên và đáng tin cậy hơn.","Chờ ít, dự tính thời gian đi, chọn giờ xuất phát.","Giảm nguy cơ đến chỗ làm muộn.")}<div class="field-value english">Investing in more <span class="gap">[1]</span> and <span class="gap">[2]</span> bus services can make daily travel easier for commuters. Shorter <span class="gap">[3]</span> and more predictable <span class="gap">[4]</span> allow them to plan when to leave home. This can <span class="gap">[5]</span> the risk of <span class="gap">[6]</span>.</div><p class="micro-note">Không có ngân hàng từ ở lượt đầu. Có thể có nhiều cách điền đúng.</p>${action("Xem lượt học viên tự điền")}`,"Tự tìm ngôn ngữ theo đúng ý đã hiểu.","Kiểm tốc độ và việc chọn từ có giữ nghĩa không.","Không điền hộ chỗ trống trước khi học viên thử.","Luyện cả từ chủ đề và từ diễn tả quan hệ, mức độ.");
add(0,"Lượt điền đầu tiên","Chọn từ cầu kỳ có thể làm đổi ý; khẳng định quá mạnh cũng cần được phát hiện.",() => `${heading("Bài điền của tôi")}<div class="field-value english">Investing in more <strong>frequent</strong> and <span class="wrong">sophisticated</span> bus services can make daily travel easier for commuters. Shorter <strong>waiting times</strong> and more predictable <strong>travel times</strong> allow them to plan when to leave home. This can <span class="wrong">eliminate</span> the risk of <strong>arriving late for work</strong>.</div>${action("Nhận feedback và tự sửa")}`,"Giữ bài lần đầu để biết mình gọi ra được gì.","Đọc những lỗi chuyển ý sang tiếng Anh.","Kiểm nghĩa, cách kết hợp từ và mức khẳng định.","Hai điểm cần sửa được nhìn thấy ngay trong câu.");
add(0,"Giữ đúng ý và mức khẳng định","Reliable giữ ý đáng tin cậy; reduce giữ ý giảm nguy cơ.",() => `${heading("Sửa ngôn ngữ")}${dialogue([["AI","Sophisticated nói về độ tinh vi. Bạn cần gọi tên đặc điểm nào giúp người đi làm dự tính giờ xe?"],["Học viên","Em muốn nói xe chạy ổn định. Em đổi thành reliable."],["Giảng viên","Dàn ý nói giảm nguy cơ hay chắc chắn không bao giờ đi muộn?"],["Học viên","Chỉ giảm nguy cơ, nên em đổi eliminate thành reduce."]])}<p class="micro-note">Travel times được chấp nhận nếu đúng nghĩa và hợp câu; không ép đổi sang từ duy nhất trong đáp án.</p>${action("Viết đoạn của mình")}`,"Tự sửa đúng phần làm đổi ý.","Giải thích mức độ, không đánh giá câu bằng độ hiếm của từ.","Chấp nhận biến thể hợp nghĩa.","Có ngôn ngữ đúng để chuyển sang dàn ý riêng.");
add(0,"Viết cả thân bài trên lớp","Học viên tự kết hợp câu chủ đề và hai ý hỗ trợ thành một đoạn.",() => `${heading("Thân bài 1 · Bản viết đầu")}<span class="status">Tự viết theo dàn ý riêng</span><div class="field"><div class="field-value english">${escape(body.replace("lowering the risk of arriving late for work", "ensuring that they will never arrive late for work"))}</div></div>${action("Nhận xét đoạn viết")}`,"Tự viết cả thân bài, thử cách nói đơn giản khi bí từ.","Kiểm cả đường ý lẫn việc câu thể hiện đúng ý.","Phản hồi sau phần viết của học viên.","Đầu ra tối thiểu là đoạn hoàn chỉnh, không phải vài câu rời.");
add(0,"Sửa đoạn và giữ sản phẩm lớp","Học viên đọc đoạn với dàn ý để tự sửa chỗ lệch.",() => `${heading("Thân bài 1 · Sau tự sửa")}${dialogue([["AI","Dàn ý nói giảm nguy cơ đi làm muộn, nhưng câu viết đang nói chắc chắn không bao giờ muộn. Bạn muốn giữ mức độ nào?"],["Học viên","Em sửa lại để nói giảm nguy cơ."]])}<div class="field-value english">${escape(body)}</div>${action("Kết thúc phần trên lớp")}`,"Sửa câu và kiểm các ý còn lại.","Người chưa xong hoàn tất đoạn; người xong có thể viết thân bài 2.","Nhận xét ngắn để học viên tự chỉnh.","Lưu dàn ý cả bài và ít nhất một thân bài hoàn chỉnh.");
add(0,"Nhận hai homework riêng","Luyện nghĩ ý nhiều đề và viết full bài phục vụ hai mục tiêu khác nhau.",() => `${heading("Homework sau buổi học")}<dl class="definition-list"><div><dt>1 · Brainstorm</dt><dd>Sáu topic, hai ý và lý do mỗi đề; có feedback và Trợ giúp.</dd></div><div><dt>2 · Bài full</dt><dd>Hoàn thành đề giao thông đã làm trên lớp; nhận điểm, TR/CC và chữa từng câu.</dd></div></dl><p class="micro-note">Sáu topic là sáu lượt nghĩ ý, không phải sáu bài essay.</p>${action("Mở bài luyện brainstorm")}`,"Biết sản phẩm cần nộp và mục đích từng nhiệm vụ.","Xác nhận sản phẩm lớp; giải thích đường học ở nhà.","Hỗ trợ học viên tự luyện và tự sửa.","Chuyển từ lớp sang luyện tập có mục đích.");
add(1,"Mở bài brainstorm sáu topic","Đề quen dùng để tập thao tác; năm đề còn lại tạo lượt nghĩ ý mới.",() => `${heading("Luyện nghĩ ý nhanh · 6 chủ đề")}<p>Mỗi đề: hướng trả lời, hai ý khác nhau và lý do ngắn. Có thể viết tiếng Việt.</p><div class="topic-list">${topics.map(([name],i) => `<div class="topic-item"><span class="number">${i+1}</span><div><strong>${escape(name)}</strong><p>${i===0?"Đề quen đã làm trên lớp":"Đề mới · tự nghĩ trước"}</p></div></div>`).join("")}</div>${action("Làm topic Công việc")}`,"Chọn đề và tự nghĩ có giờ.","Xem kết quả sau để chọn lỗi cần chữa tiếp.","Chưa đưa sẵn danh sách ý.","Có số lượt luyện để tăng tốc và độ ổn định.");
add(1,"Topic Công việc: tự nghĩ hai ý","Lượt đầu được giữ riêng để nhìn đúng khả năng tự brainstorm.",() => `${heading("Topic 3 / 6 · Công việc","Lượt đầu · 02:00")}${question(topics[2][1])}${field("Hướng trả lời","Khá đồng ý nếu công việc làm từ xa được và phối hợp vẫn rõ.")}${field("Ý 1 và lý do","Không đi lại, tiết kiệm thời gian để nghỉ ngơi.")}${field("Ý 2 và lý do","Có thêm thời gian cho gia đình vì không phải di chuyển.")}${action("Gửi nhận xét")}`,"Tự ghi hai hướng và lý do.","Không nhầm thời gian chờ AI với thời gian tự nghĩ.","Đọc hai ý để kiểm khác biệt thực sự.","Giữ nguyên phiên bản lần đầu khi hết giờ.");
add(1,"AI phát hiện hai ý gần trùng","Học viên tự chọn một góc nhìn khác và làm rõ điều kiện.",() => `${heading("Feedback cho hai ý")}${dialogue([["AI","Cả hai ý đang đi từ thời gian di chuyển được tiết kiệm. Ngoài thời gian, chi phí hoặc lựa chọn nơi ở có thay đổi gì?"],["Học viên","Em đổi ý 2 sang chọn nơi ở xa hơn, không nhất thiết thuê gần văn phòng."],["AI","Điều kiện nào khiến lựa chọn đó thực hiện được?"],["Học viên","Phải làm từ xa đủ thường xuyên, không phải vẫn đến văn phòng gần như mỗi ngày."]])}${action("Xem lượt cần trợ giúp")}`,"Tự sửa, giữ điều kiện để ý đủ rõ.","Kiểm cách AI hiểu ý nếu học viên phản đối.","Hỏi một điểm cần làm rõ, không viết cả chuỗi hộ.","Hai ý có hướng chứng minh riêng.");
add(1,"Khi bí: nhấn Trợ giúp","Trợ giúp trả câu hỏi gợi mở, không trả bài làm hoàn chỉnh.",() => `${heading("Topic 2 / 6 · Giáo dục","Lượt có hỗ trợ")}${question(topics[1][1])}${field("Ý đang có","Em chưa nghĩ ra một lợi ích cụ thể.",true)}${dialogue([["AI · Câu hỏi trợ giúp","Sau khi biết kiến thức trong sách, trong một hoạt động ngoài lớp, học sinh có thể phải tự làm hoặc tự quyết định việc gì?"]])}${action("Xem học viên trả lời gợi ý","help")}`,"Nhấn Trợ giúp và tự trả lời câu hỏi.","Xem người thường xuyên cần nhiều gợi ý.","Thu hẹp góc nhìn theo đúng đề.","Lượt này được ghi rõ là có hỗ trợ.");
add(1,"Từ câu hỏi trợ giúp đến ý của mình","Học viên gọi tên kết quả và lý do bằng lời của mình.",() => `${heading("Tôi tự nghĩ tiếp")}${dialogue([["Học viên","Học sinh có thể tự quan sát và lấy thông tin ngoài thực tế."],["AI","Việc đó giúp học sinh dùng kiến thức đã học ra sao?"],["Học viên","Các bạn hiểu khi nào kiến thức dùng được, chứ không chỉ nhớ lý thuyết."]])}${field("Ý tôi giữ lại","Hoạt động thực tế giúp học sinh biết vận dụng kiến thức; họ tự thu thập thông tin rồi dùng điều đã học để giải thích.")}${action("Xem tổng hợp sáu topic")}`,"Tự ghi ý và thử hướng thứ hai.","Phân biệt bí chủ đề với chưa biết chọn góc nhìn.","Sau vài câu vẫn bế tắc, ghi Cần giảng viên xem và cho tiếp tục đề khác.","Ý được tự nghĩ ra, không tính một ý AI bịa là sản phẩm học viên.");
add(1,"Hoàn thành bài luyện brainstorm","Giảng viên nhìn được cả chất lượng ý, thời gian và mức cần hỗ trợ.",() => `${heading("Kết quả bài luyện · 6 topic")}<span class="status good">Đã nộp phiếu luyện minh họa</span><div class="table-wrap"><table class="compact"><thead><tr><th>Topic</th><th>Hai hướng sau tự sửa</th><th>Lượt đầu</th><th>Trợ giúp</th></tr></thead><tbody><tr><td>Giao thông</td><td>Thời gian đi làm; chi phí đi lại</td><td>01:20 · đề quen</td><td>Không</td></tr><tr><td>Giáo dục</td><td>Vận dụng kiến thức; kỹ năng phối hợp</td><td>02:00</td><td>2 câu hỏi</td></tr><tr><td>Công việc</td><td>Thời gian nghỉ; lựa chọn nơi ở</td><td>01:48</td><td>Feedback ý trùng</td></tr><tr><td>Công nghệ</td><td>Mất tập trung; liên lạc với gia đình</td><td>01:55</td><td>Không</td></tr><tr><td>Quảng cáo</td><td>Đòi mua đồ; nhận biết thông tin</td><td>02:00</td><td>Cần làm rõ</td></tr><tr><td>Đô thị</td><td>Không gian vận động; nơi gặp gỡ</td><td>01:42</td><td>Không</td></tr></tbody></table></div>${field("Tôi tự rút ra","Hay nêu hai ý cùng một cơ chế. Lượt sau em kiểm sự khác biệt trước khi gửi.")}${action("Mở nhiệm vụ viết full bài")}`,"Xem lại ý ban đầu, ý sau sửa và câu hỏi còn mắc.","Chọn một vài ca để can thiệp ở buổi sau.","Tổng hợp đúng lượt tự nghĩ và lượt có hỗ trợ.","Bài brainstorm đã nộp; trạng thái còn mắc vẫn được giữ.");
add(2,"Mở homework viết full bài","Học viên đã có nền tảng để hoàn thành cả bài.",() => `${heading("Hoàn thành bài Task 2")}${question()}<ul class="check-list"><li>Dàn ý toàn bài đã làm trên lớp.</li><li>Thân bài 1 đã viết và tự sửa.</li><li>Cần bổ sung mở bài, thân bài 2 và kết bài.</li></ul>${field("Kết quả sẽ nhận","Điểm và bốn tiêu chí như bài Test; TR/CC chi tiết; nhận xét từng câu.")}${action("Xem bản full lần đầu")}`,"Đọc lại dàn ý, viết các phần còn thiếu và chỉnh toàn bài.","Đã giao tiêu chí đầu ra và cách dùng feedback.","Nhận xét sau khi học viên có bản viết.","Nhiệm vụ viết full riêng với sáu topic brainstorm.");
add(2,"Viết bản full lần đầu","Giữ thời gian và điều kiện làm bài để đọc điểm đúng nghĩa.",() => `${heading("Bài full của tôi")}<span class="status">Đề đã được chuẩn bị trên lớp</span>${htmlEssay()}<p class="micro-note">${essayParagraphs.join(" ").split(/\s+/).length} từ · Thời gian hoàn thành minh họa: 24 phút · Tự viết từ dàn ý đã chữa.</p>${action("Kiểm tra trước khi nộp")}`,"Tự hoàn thành cả bài và đọc lại quan điểm.","Sau khi nộp, đối chiếu bài với dàn ý để tìm chỗ lệch.","Không sinh essay thay học viên.","Có bản đầu để chấm và theo dõi tiến bộ.");
add(2,"Nộp homework full bài","Học viên biết rõ mình nộp bản nào và sẽ nhận kết quả gì.",() => `${heading("Kiểm tra bài nộp")}<ul class="check-list"><li>Đủ mở bài, hai thân bài và kết bài.</li><li>Giữ bản full lần đầu để so với bản chỉnh.</li><li>Ghi điều kiện: đề đã được chữa trên lớp.</li></ul>${field("Học viên muốn hỏi","Em chưa chắc kết luận có giữ đúng quan điểm giới hạn ở mở bài không.")}${action("Nộp bài minh họa")}`,"Nộp đúng bản đầu và câu hỏi muốn giảng viên xem.","Nhìn được băn khoăn của người học khi đọc bài.","Chuẩn bị hai loại kết quả: điểm và chữa chi tiết.","Một lần nộp gắn với đúng bản bài viết.");
add(2,"Đã nhận bài, đang chấm","Tách việc nhận bài với việc đã có đủ điểm và feedback.",() => `<div class="receipt"><div class="receipt-icon">✓</div><h3>Đã nhận homework</h3><p class="muted">Bản full lần đầu đã được giữ trong tình huống minh họa.</p><p><span class="status">Đang chấm điểm và tạo nhận xét</span></p><p class="micro-note">Điểm và feedback xuất hiện khi có đủ kết quả. Demo dùng Next để chuyển tới màn kết quả đã chuẩn bị.</p>${action("Xem kết quả chấm minh họa")}</div>`,"Nhìn trạng thái và biết bài đã được nhận.","Xem tiến độ; không coi nhận bài là đã chấm xong.","Chấm tổng thể và chữa chi tiết theo yêu cầu chương trình.","Trạng thái chờ không bị trình bày thành điểm hoàn tất.");
add(3,"Xem điểm và mức hiện tại","Điểm như bài Test giúp học viên biết mình đang viết tốt đến đâu.",() => `${heading("Kết quả bài full")}<span class="status attention">Điểm minh họa · Không phải chấm thật</span><div class="score-top"><div><div class="band">6.5</div><p class="score-caption">Điểm Task 2</p></div><div class="score-intro"><strong>Bài có nền tảng rõ, còn hai điểm cần sửa.</strong><p class="muted">Kết luận đang lệch quan điểm mở bài; một câu khẳng định quá tuyệt đối.</p></div></div><div class="criteria">${[["TR",6,"Trả lời đề"],["CC",7,"Mạch và liên kết"],["LR",7,"Từ vựng"],["GRA",6,"Ngữ pháp"]].map(([n,v,l]) => `<div class="criterion"><span>${n}</span><strong>${v.toFixed(1)}</strong><span>${l}</span></div>`).join("")}</div><p>Ưu tiên sửa sự nhất quán của quan điểm, rồi rà lại mức khẳng định và ngôn ngữ trong từng câu.</p>${action("Xem tiến bộ và mức thi dự kiến")}`,"Đọc điểm tổng, bốn tiêu chí và điều ưu tiên.","Kiểm đánh giá có phù hợp với bài và giải đáp phản đối.","Trả đánh giá tổng thể theo cách chấm Test.","Biết mức hiện tại ngay khi báo cáo chấm có đủ.");
add(3,"Theo dõi tiến bộ và dự báo mức thi","So bài cùng điều kiện; ưu tiên bài tự làm có giờ khi ước lượng mức thi.",() => `${heading("Tiến bộ Writing Task 2")}${field("Mục tiêu","7.0 trở lên") }<div class="table-wrap"><table><thead><tr><th>Bài minh họa</th><th>Điều kiện</th><th>Điểm bản đầu</th></tr></thead><tbody><tr><td>Lần 1</td><td>Đề mới, tự làm có bấm giờ</td><td>6.0</td></tr><tr><td>Lần 2</td><td>Đề mới, tự làm có bấm giờ</td><td>6.5</td></tr><tr><td>Homework hôm nay</td><td>Dàn ý đã chữa trên lớp</td><td>6.5</td></tr></tbody></table></div>${field("Mức thi dự kiến · Minh họa","Khoảng 6.0–6.5 ở Task 2, dựa trên các bài tự làm có giờ. Cần thêm bài mới để cập nhật mức dự kiến.")}${field("Việc cần làm tiếp","Giữ quan điểm từ mở đến kết; luyện tự triển khai đủ nhanh, sau đó kiểm bằng bài full đề mới có bấm giờ.")}${action("Đọc nhận xét TR và CC")}`,"Nhìn xu hướng và khoảng cách tới mục tiêu.","Đối chiếu chất lượng với thời gian, số lượt hỗ trợ.","Tổng hợp có phân biệt điều kiện làm và lượt sửa.","Điểm bài đã chữa không bị dùng như bằng chứng duy nhất về phòng thi.");
add(3,"Đọc TR và CC chi tiết","Chữa ở cấp toàn bài và đoạn trước khi xem từng câu.",() => `${heading("Trả lời đề và mạch lập luận")}<section class="feedback-block"><h4>TR · Quan điểm</h4><p>Mở bài ưu tiên theo bối cảnh. Kết bài lại yêu cầu dừng mọi đầu tư đường. Điều đó mâu thuẫn với thân bài 2 và quan điểm ban đầu.</p></section><section class="feedback-block"><h4>CC · Đường phát triển</h4><p>Hai thân bài đã có chức năng riêng. Ở ý đi làm đúng giờ, kiểm xem kết quả được giải thích và mức khẳng định có giữ đúng dàn ý không.</p></section>${dialogue([["AI","Quan điểm nào là quan điểm bạn muốn giữ xuyên suốt bài?"],["Học viên","Em muốn giữ ưu tiên theo bối cảnh. Em đã viết kết luận quá mạnh."]])}${action("Mở chữa từng câu")}`,"Đối chiếu nhận xét với đúng phần bài làm.","Gỡ lựa chọn ý và tổ chức bài nếu học viên chưa hiểu.","Chấm TR/CC theo cách Writing 56–67.","Học viên hiểu lý do, không chỉ nhìn con số.");
add(3,"Xem từng câu: sửa chỗ nào, vì sao","Chọn câu để xem câu gốc, giải thích và phần sửa gợi ý.",() => `${heading("Chữa từng câu")}<div class="sentence-picker" aria-label="Chọn câu minh họa"><button class="sentence-button active" data-sentence="0" type="button">Câu về đi làm muộn</button><button class="sentence-button" data-sentence="1" type="button">Câu kết bài</button><button class="sentence-button" data-sentence="2" type="button">Một câu đã rõ</button></div><div id="sentence-detail"></div><p class="micro-note">Ba câu được chọn để minh họa cách đọc. Trong sản phẩm đầy đủ, học viên xem các câu của toàn bài.</p>${action("Tự sửa và nộp bản chỉnh")}`,"Đọc câu gốc, hiểu lý do và tự sửa trong ngữ cảnh.","Giải thích điểm chưa hiểu, không viết lại toàn bài.","Giữ đúng vị trí lỗi; gợi sửa phần cần thiết, không tạo lỗi giả.","Điểm cho biết mức hiện tại; chữa từng câu cho biết cách cải thiện.");
add(3,"Nộp bản tự sửa","Học viên giữ bản đầu, bản sửa và lý do thay đổi.",() => `${heading("Bản chỉnh của tôi")}${field("Sửa ý đi làm muộn","They can therefore choose when to leave home, reducing the risk of arriving late for work.")}${field("Sửa kết bài","In conclusion, public transport should be prioritised in crowded cities with existing road networks, while investment in basic road connections remains necessary elsewhere.")}${field("Tôi đã sửa gì và vì sao?","Giữ mức giảm nguy cơ thay vì chắc chắn; đưa kết luận về đúng quan điểm theo bối cảnh.")}${action("Nộp bản chỉnh minh họa")}`,"Tự chỉnh theo lý do đã hiểu và nộp lại đúng phiên bản.","Xem học viên đã vận dụng feedback được không.","Nếu chấm lại, ghi rõ đây là điểm sau tự sửa.","Không nhầm bản sau feedback với năng lực tự viết lần đầu.");
add(3,"Kết thúc hành trình của buổi học","Toàn bộ sản phẩm được nối từ lớp đến homework và kết quả chấm.",() => `${heading("Hồ sơ học tập sau buổi Writing")}<span class="status good">Đã hoàn tất hành trình minh họa</span><div class="finish-summary"><p><strong>Trên lớp</strong><br>Dàn ý toàn bài + bài huy động từ vựng + một thân bài hoàn chỉnh.</p><p><strong>Ở nhà</strong><br>Phiếu brainstorm sáu topic + bản full lần đầu + bản tự sửa.</p><p><strong>Đánh giá</strong><br>Điểm Task 2 và bốn tiêu chí + TR/CC chi tiết + chữa từng câu + thời gian, điều kiện làm bài.</p><p><strong>Buổi sau</strong><br>Giảng viên xem câu hỏi còn mắc; tiếp tục luyện chất lượng và tốc độ bằng ý quen thuộc với từng người.</p></div><div class="actions"><button class="button primary" data-action="restart" type="button">Xem lại từ đầu</button></div>`,"Biết đã học gì, nộp gì và cần luyện gì tiếp.","Chọn can thiệp tiếp theo từ bài thật và lịch sử học viên.","Giữ kết quả minh họa theo đúng từng loại bài.","Hành trình đầy đủ: bắt đầu lớp → học → nộp homework → có điểm → tự sửa.");

const sentenceFeedback = [
  {original:"Commuters will never be late for work if the city invests in buses.",reason:"Will never biến giảm nguy cơ thành chắc chắn. Đầu tư xe buýt chưa loại bỏ mọi nguyên nhân đi muộn; cần giữ mức khẳng định của dàn ý.",revision:"Gợi sửa phần kết quả: can reduce the risk of arriving late for work. Đọc lại các câu trước để giữ cơ chế chọn giờ xuất phát."},
  {original:essayParagraphs[3],reason:"Câu kết bỏ mất điều kiện ở đô thị và mâu thuẫn với thân bài 2 về đường kết nối. Đây là lỗi về quan điểm, không chỉ từ vựng.",revision:"Tự viết lại kết luận với cả hai phần: ưu tiên dịch vụ ở đô thị đã có đường; giữ đầu tư đường cần thiết ở nơi thiếu kết nối."},
  {original:"Services with reasonable fares and suitable routes may also provide an alternative to private vehicles.",reason:"Câu đã giữ điều kiện giá vé, tuyến phù hợp và mức có thể. Không cần thay chỉ để dùng từ lạ hơn.",revision:"Giữ câu này; kiểm câu tiếp theo có giải thích chi phí nào giảm và kết quả B là gì."}
];

let index = 0;
const select = document.querySelector("#step-select");
select.innerHTML = steps.map((step,i) => `<option value="${i}">${i+1}. ${escape(step.title)}</option>`).join("");
const chapterNav = document.querySelector("#chapters");
chapterNav.innerHTML = chapters.map((chapter,i) => `<button class="chapter-button" data-chapter="${i}" type="button"><span class="chapter-number">${i+1}</span><span><strong>${escape(chapter.title)}</strong><small>${escape(chapter.detail)}</small></span></button>`).join("");

function renderSentence(which = 0) {
  const item = sentenceFeedback[which];
  const target = document.querySelector("#sentence-detail");
  if (!target || !item) return;
  target.innerHTML = `<section class="feedback-block"><h4>Câu gốc</h4><p class="essay">${escape(item.original)}</p></section><section class="feedback-block"><h4>Nhận xét và giải thích</h4><p>${escape(item.reason)}</p></section><section class="feedback-block"><h4>Sửa hoặc giữ câu</h4><p>${escape(item.revision)}</p></section>`;
  document.querySelectorAll("[data-sentence]").forEach(button => { button.classList.toggle("active", Number(button.dataset.sentence) === which); button.setAttribute("aria-pressed", String(Number(button.dataset.sentence) === which)); });
}

// URL giữ số bước để có thể gửi thẳng một màn và tải lại; hash sai quay về bước đầu.
function readHash() {
  const match = location.hash.match(/^#buoc=(\d+)$/);
  const value = match ? Number(match[1]) : 1;
  return Number.isSafeInteger(value) && value >= 1 && value <= steps.length ? value - 1 : 0;
}
function render(focus = false) {
  const step = steps[index];
  document.querySelector("#chapter-label").textContent = chapters[step.chapter].title;
  document.querySelector("#screen-title").textContent = step.title;
  document.querySelector("#screen-intro").textContent = step.intro;
  document.querySelector("#step-count").textContent = `${index+1} / ${steps.length}`;
  document.querySelector("#screen-context").textContent = step.chapter === 0 ? "Buổi học trên lớp · Học viên giả định" : "Ở nhà · Học viên giả định";
  document.querySelector("#screen-body").innerHTML = step.screen();
  document.querySelector("#student-note").textContent = step.student;
  document.querySelector("#teacher-note").textContent = step.teacher;
  document.querySelector("#ai-note").textContent = step.ai;
  document.querySelector("#outcome").textContent = `Kết quả bước này: ${step.outcome}`;
  document.querySelector("#previous").disabled = index === 0;
  document.querySelector("#next").disabled = index === steps.length - 1;
  const progress = document.querySelector("#progress");
  progress.max = steps.length;
  progress.value = index + 1;
  document.querySelector("#progress-label").textContent = `Bước ${index+1} trên ${steps.length}`;
  select.value = String(index);
  document.querySelectorAll("[data-chapter]").forEach(button => { const active = Number(button.dataset.chapter) === step.chapter; button.classList.toggle("active", active); if (active) button.setAttribute("aria-current", "step"); else button.removeAttribute("aria-current"); });
  renderSentence();
  document.title = `${step.title} | Demo Writing 7+`;
  if (focus) { window.scrollTo(0,0); document.querySelector("#screen-title").focus({preventScroll:true}); }
}
function go(nextIndex) {
  if (!Number.isInteger(nextIndex) || nextIndex < 0 || nextIndex >= steps.length) return;
  index = nextIndex;
  history.pushState(null,"",`#buoc=${index+1}`);
  render(true);
}
document.querySelector("#previous").addEventListener("click", () => go(index - 1));
document.querySelector("#next").addEventListener("click", () => go(index + 1));
document.querySelector("#restart").addEventListener("click", () => go(0));
select.addEventListener("change", () => go(Number(select.value)));
document.addEventListener("click", event => {
  const chapter = event.target.closest("[data-chapter]");
  if (chapter) go(steps.findIndex(step => step.chapter === Number(chapter.dataset.chapter)));
  const actionButton = event.target.closest("[data-action]");
  if (actionButton) go(actionButton.dataset.action === "restart" ? 0 : index + 1);
  const sentence = event.target.closest("[data-sentence]");
  if (sentence) renderSentence(Number(sentence.dataset.sentence));
});
document.addEventListener("keydown", event => {
  if (event.altKey || event.ctrlKey || event.metaKey || event.shiftKey || event.target.closest("select,input,textarea,[contenteditable]")) return;
  if (event.key === "ArrowRight") { event.preventDefault(); go(index+1); }
  if (event.key === "ArrowLeft") { event.preventDefault(); go(index-1); }
});
window.addEventListener("popstate", () => { index = readHash(); render(true); });
window.addEventListener("hashchange", () => { index = readHash(); render(true); });
index = readHash();
render();
