import { createTeacherApi } from './api.js?rev=20260920-dashboard-audit-v3';
import { createRequestId } from './core.js';
import { teacherAuthFailure } from './teacher-auth-ui.js';
import { coverageDescription, coverageStatusLabels } from './writing-flow-coverage.js';
import { createTeacherLoginPreference } from '../../shared/teacher-login-preference.js?rev=20260918-v1';
import { createTeacherSessionClient } from '../../shared/teacher-session-client.js?rev=20260920-v1';

// Trang chỉ tải danh sách nhẹ. Nội dung bài, Text chấm bài và log được tải khi mở một dòng.
// Mọi thao tác retry/bỏ qua đều ghi yêu cầu qua API; trang không ghi Lark Base.
const $ = id => document.getElementById(id);
const stages = ['intake', 'precheck', 'main', 'critic', 'arbiter', 'render', 'deliver'];
const stageNames = { intake: 'Tiếp nhận', precheck: 'Kiểm trước khi chấm', main: 'Chấm chính',
  critic: 'Phản biện', arbiter: 'Phân xử', render: 'Tạo trang kết quả', deliver: 'Ghi link vào homework' };
const stageWorkflowIds = { intake: 'zxSd0xBPJzMqQlWt', precheck: 'P2p5N7iZzwHFDufk',
  main: 'X0qzwWc5CgBzgOWT', critic: '4o6jEwyQM4U29XU6', arbiter: 'yFdVOEBVhLitToQD',
  render: 'o8uncH0TWsJybeS2', deliver: 'KqWtSbjkHDMSAgbN' };
const statusNames = { received: 'Chờ chấm', running: 'Đang xử lý', needs_review: 'Cần kiểm tra',
  delivered: 'Đã giao', superseded: 'Có bản mới', pending: 'Đang chờ', succeeded: 'Đã xong',
  skipped: 'Đã bỏ qua', failed: 'Lỗi', paused: 'Tạm dừng', scanning: 'Đang quét' };
const viewMeta = {
  overview: ['Toàn hệ thống', 'Tổng quan vận hành', 'Các số cần chú ý và tình trạng quét lớp.', 'Tất cả trạng thái'],
  daily: ['Thống kê', 'Số bài chấm xong theo ngày', 'Lọc theo lớp, giảng viên, loại bài và khoảng ngày.', 'Đã giao cho học viên'],
  classes: ['Theo lớp', 'Không gian lớp', 'Xem trạng thái nguồn và yêu cầu quét riêng từng lớp đang học.', 'Lớp approved + on_going'],
  completed_classes: ['Lưu trữ', 'Các lớp đã hoàn thành', 'Không nằm trong lượt quét và các view vận hành hằng ngày.', 'Không quét tự động'],
  mapping: ['Nguồn lớp', 'Lớp cần ghép hoặc kiểm tra', 'Các lớp thiếu trạng thái, trùng mapping hoặc chưa đủ điều kiện quét.', 'Đang tạm dừng'],
  review: ['Cần xử lý', 'Bài đã lỗi ba lần', 'Kiểm tra nguyên nhân rồi chạy lại đúng bước đang lỗi.', 'Cần kiểm tra'],
  source: ['Cần xử lý', 'Tài liệu hoặc bài không hợp lệ', 'Sai loại file, sai đề hoặc sai format bảng được giữ riêng tại đây.', 'Dừng trước khi gọi AI'],
  skipped: ['Thùng rác mềm', 'Các bài đã bỏ qua', 'Có thể khôi phục bài bị bỏ qua nhầm.', 'Đã bỏ qua'],
  delivered: ['Kết quả', 'Các bài đã giao', 'Link kết quả đã được ghi và đọc lại thành công.', 'Đã giao'],
  legacy: ['Chuyển đổi', 'Lịch sử từ luồng cũ', 'Dữ liệu cũ chỉ dùng để xem lại theo lớp.', 'Chỉ đọc'],
  logs: ['Điều tra lỗi', 'Nhật ký lỗi kỹ thuật', 'Mã workflow, node lỗi, số lần gặp và link mở n8n.', '7 ngày gần nhất'],
  audit: ['Dấu vết vận hành', 'Nhật ký thao tác', 'Ai đã retry, bỏ qua, khôi phục, quét lớp hoặc thay đổi trạng thái lớp.', 'Mới nhất trước'],
};
for (const [index, stage] of stages.entries()) viewMeta[stage] = ['7 giai đoạn',
  `${index + 1}. ${stageNames[stage]}`, 'Mỗi bài ở đây đang chờ, chạy hoặc cần xử lý tại đúng giai đoạn này.',
  `Đang ở bước: ${stageNames[stage]}`];

const columns = {
  student: ['Học viên / tên thủ công', row => sourceName(row)],
  class: ['Lớp', row => row.class_code || '—'],
  teacher: ['Giảng viên', row => (row.teacher_names || []).join(', ') || '—'],
  file: ['File Doc', row => externalLink(row.file_url, 'Mở Google Docs', row.homework_file_id || '—')],
  classroom: ['Classroom', row => externalLink(row.classroom_url, 'Mở Classroom', '—')],
  trcc: ['TRCC', row => row.tr_cc_check == null ? '—' : row.tr_cc_check ? 'Có' : 'Không'],
  sourceStatus: ['Trạng thái nguồn', row => row.source_status || '—'],
  finished: ['Thời điểm xong', row => formatTime(row.finished_at)],
  topic: ['Đề bài', row => row.topic || '—'],
  image: ['Ảnh biểu đồ', row => externalLink(row.image_url, 'Mở ảnh', '—')],
  created: ['Ngày tạo', row => formatTime(row.source_created_at || row.created_at)],
  content: ['Nội dung', row => detailButton(row, 'Xem nội dung')],
  grading: ['Text chấm bài', row => row.grading_text_available ? detailButton(row, 'Xem Text chấm bài') : 'Chưa có'],
  attempts: ['Số lần thử', row => Number(row.attempt_count || 0)],
  error: ['Lỗi gần nhất', row => row.last_error_code || '—'],
  actions: ['Thao tác', row => actionCell(row)],
};
const defaultColumns = ['student', 'class', 'teacher', 'file', 'classroom', 'trcc', 'finished', 'actions'];
const loginPreference = createTeacherLoginPreference(() => window.localStorage);
const state = { authenticated: false, api: null, timer: null, searchTimer: null, sessionClient: null,
  loginGeneration: 0, activeView: 'overview', pairs: [], nextCursor: null, loadingMore: false,
  counts: null, summary: [], coverage: [], reviews: [], issues: [], failures: [], events: [], legacy: [],
  activeClasses: [], completedClasses: [], daily: [], filtersLoaded: false,
  visibleColumns: readColumns(), pinnedClasses: readClassList('writing-flow:pinned-classes:v1'),
  recentClasses: readClassList('writing-flow:recent-classes:v1') };

function makeText(tag, value, className = '') { const node = document.createElement(tag); node.textContent = String(value ?? ''); if (className) node.className = className; return node; }
function showError(id, message = '') { const node = $(id); node.textContent = message; node.hidden = !message; }
function formatTime(value) { return value ? new Date(value).toLocaleString('vi-VN') : '—'; }
function sourceName(row) { return row.student_name || row.display_name || 'Chưa có tên'; }
function externalLink(url, label, fallback) { if (!url) return fallback; const link = makeText('a', label); link.href = url; link.target = '_blank'; link.rel = 'noopener noreferrer'; return link; }
function actionButton(label, handler, className = 'secondary') { const button = makeText('button', label); button.type = 'button'; button.className = className; button.addEventListener('click', handler); return button; }
function readColumns() { try { const value = JSON.parse(localStorage.getItem('writing-flow:columns:v1') || 'null'); return Array.isArray(value) && value.every(key => columns[key]) ? value : defaultColumns; } catch { return defaultColumns; } }
function saveColumns() { try { localStorage.setItem('writing-flow:columns:v1', JSON.stringify(state.visibleColumns)); } catch { /* Vẫn dùng được lựa chọn trong phiên hiện tại. */ } }
function readClassList(key) { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value.filter(item => typeof item === 'string').slice(0, 12) : []; } catch { return []; } }
function saveClassList(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* Danh sách ghim/gần đây chỉ là tiện ích giao diện. */ } }
function currentFilters(extra = {}) { return { classCode: $('flow-class').value, teacherName: $('flow-teacher').value,
  taskType: $('flow-task-type').value, search: $('flow-search').value.trim(),
  stageStatus: stages.includes(state.activeView) ? $('flow-stage-status').value : '',
  dateFrom: $('flow-date-from').value, dateTo: $('flow-date-to').value, limit: 50, ...extra }; }
function pairViewFilters() { if (stages.includes(state.activeView)) return { stageKey: state.activeView };
  if (state.activeView === 'skipped') return { view: 'skipped' };
  if (state.activeView === 'delivered') return { view: 'delivered' };
  return state.activeView === 'classes' ? {} : { view: 'unfinished' }; }

function renderColumnChoices() {
  const root = $('flow-field-choices'); root.replaceChildren(makeText('legend', 'Cột hiển thị'));
  const ordered = [...state.visibleColumns, ...Object.keys(columns).filter(key => !state.visibleColumns.includes(key))];
  const move = (key, delta) => { const index = state.visibleColumns.indexOf(key); if (index < 0) return; const target = index + delta; if (target < 0 || target >= state.visibleColumns.length) return; [state.visibleColumns[index], state.visibleColumns[target]] = [state.visibleColumns[target], state.visibleColumns[index]]; saveColumns(); renderColumnChoices(); renderPairs(); };
  for (const key of ordered) {
    const label = columns[key][0]; const line = document.createElement('div'); line.className = 'flow-column-choice'; line.draggable = state.visibleColumns.includes(key); line.dataset.key = key;
    const input = document.createElement('input'); input.type = 'checkbox'; input.checked = state.visibleColumns.includes(key); input.value = key;
    input.addEventListener('change', () => { if (input.checked) state.visibleColumns.push(key); else if (state.visibleColumns.length > 1) state.visibleColumns = state.visibleColumns.filter(item => item !== key); else input.checked = true; saveColumns(); renderColumnChoices(); renderPairs(); });
    const grip = makeText('span', '⋮⋮', 'flow-column-grip'); grip.title = 'Kéo để đổi thứ tự';
    const up = actionButton('↑', () => move(key, -1)); up.title = 'Đưa cột sang trái'; up.disabled = !input.checked || state.visibleColumns.indexOf(key) <= 0;
    const down = actionButton('↓', () => move(key, 1)); down.title = 'Đưa cột sang phải'; down.disabled = !input.checked || state.visibleColumns.indexOf(key) < 0 || state.visibleColumns.indexOf(key) === state.visibleColumns.length - 1;
    line.append(input, document.createTextNode(label), up, down); line.prepend(grip);
    line.addEventListener('dragstart', event => { line.dataset.dragging = 'true'; event.dataTransfer?.setData('text/plain', key); });
    line.addEventListener('dragend', () => { delete line.dataset.dragging; });
    line.addEventListener('dragover', event => event.preventDefault());
    line.addEventListener('drop', event => { event.preventDefault(); const source = event.dataTransfer?.getData('text/plain'); const from = state.visibleColumns.indexOf(source); const to = state.visibleColumns.indexOf(key); if (from < 0 || to < 0 || from === to) return; state.visibleColumns.splice(from, 1); state.visibleColumns.splice(to, 0, source); saveColumns(); renderColumnChoices(); renderPairs(); });
    root.append(line);
  }
}

function renderHeading() { const meta = viewMeta[state.activeView]; $('flow-view-kicker').textContent = meta[0]; $('flow-view-title').textContent = meta[1]; $('flow-view-help').textContent = meta[2]; const badge = $('flow-view-status'); badge.textContent = meta[3]; badge.dataset.tone = ['review', 'source', 'logs'].includes(state.activeView) ? 'danger' : ['delivered', 'completed_classes'].includes(state.activeView) ? 'success' : ''; const breakdown = $('flow-stage-breakdown'); breakdown.replaceChildren(); breakdown.hidden = !stages.includes(state.activeView); if (!breakdown.hidden) { const rows = (state.counts?.stages || []).filter(row => row.stage_key === state.activeView && !row.skipped); const totals = new Map(rows.map(row => [row.stage_status, Number(row.pair_count || 0)])); for (const key of ['pending', 'running', 'needs_review', 'succeeded']) breakdown.append(makeText('span', `${statusNames[key]}: ${totals.get(key) || 0}`)); } for (const button of document.querySelectorAll('#flow-views [data-view]')) button.setAttribute('aria-pressed', String(button.dataset.view === state.activeView)); }
function setViewVisibility() { const map = { overview: ['flow-overview-section'], daily: ['flow-daily-section'], classes: ['flow-classes-section', 'flow-pairs-section'], completed_classes: ['flow-classes-section'], mapping: ['flow-mapping-section'], review: ['flow-reviews-section'], source: ['flow-source-section'], logs: ['flow-technical-section'], audit: ['flow-audit-section'], legacy: ['flow-legacy-section'] }; const visible = map[state.activeView] || ['flow-pairs-section']; for (const id of ['flow-overview-section', 'flow-daily-section', 'flow-classes-section', 'flow-reviews-section', 'flow-source-section', 'flow-technical-section', 'flow-audit-section', 'flow-mapping-section', 'flow-pairs-section', 'flow-legacy-section']) $(id).hidden = !visible.includes(id); if (state.activeView === 'classes' && !$('flow-class').value) $('flow-pairs-section').hidden = true; $('flow-stage-status-filter').hidden = !stages.includes(state.activeView); renderHeading(); }

function renderCounts() {
  const values = { overview: 0, classes: state.activeClasses.length, completed_classes: state.completedClasses.length,
    mapping: state.coverage.filter(row => !['covered', 'completed', 'excluded'].includes(row.status)).length,
    review: Number(state.counts?.support?.reviews || 0), source: Number(state.counts?.support?.source_issues || 0),
    skipped: 0, delivered: 0 };
  for (const stage of stages) values[stage] = 0;
  for (const row of state.counts?.stages || []) { const count = Number(row.pair_count || 0); values.overview += count; if (row.skipped) values.skipped += count; else { values[row.stage_key] = (values[row.stage_key] || 0) + count; if (row.stage_key === 'deliver' && row.stage_status === 'succeeded') values.delivered += count; } }
  for (const [key, value] of Object.entries(values)) { const node = document.querySelector(`[data-count="${key}"]`); if (node) node.textContent = String(value); }
}
function renderSummary() { const root = $('flow-summary'); root.replaceChildren(); const stageRows = state.counts?.stages || []; const skipped = stageRows.filter(row => row.skipped).reduce((sum, row) => sum + Number(row.pair_count || 0), 0); const delivered = stageRows.filter(row => !row.skipped && row.stage_key === 'deliver' && row.stage_status === 'succeeded').reduce((sum, row) => sum + Number(row.pair_count || 0), 0); const running = stageRows.filter(row => !row.skipped && row.stage_status === 'running').reduce((sum, row) => sum + Number(row.pair_count || 0), 0); const attention = Number(state.counts?.support?.reviews || 0) + Number(state.counts?.support?.source_issues || 0); for (const item of [{ key: 'running', label: 'Đang xử lý', value: running }, { key: 'needs_review', label: 'Cần xử lý', value: attention }, { key: 'delivered', label: 'Đã giao', value: delivered }, { key: 'skipped', label: 'Đã bỏ qua', value: skipped }]) { const card = document.createElement('article'); card.dataset.status = item.key; card.append(makeText('strong', item.value), makeText('span', item.label)); root.append(card); } }

function populateFilters(filters) { const currentClass = $('flow-class').value; const currentTeacher = $('flow-teacher').value; const active = (filters.classes || []).filter(row => row.enabled && row.mapping_status === 'approved' && row.class_status === 'on_going'); $('flow-class').replaceChildren(new Option('Tất cả lớp đang học', '')); for (const row of active) $('flow-class').append(new Option(`${row.class_code}${row.classroom_name ? ` · ${row.classroom_name}` : ''}`, row.class_code)); $('flow-class').value = active.some(row => row.class_code === currentClass) ? currentClass : ''; $('flow-teacher').replaceChildren(new Option('Tất cả giảng viên', '')); for (const name of filters.teachers || []) $('flow-teacher').append(new Option(name, name)); $('flow-teacher').value = (filters.teachers || []).includes(currentTeacher) ? currentTeacher : ''; }

async function requestClassScan(classCode, button) { const reason = prompt(`Lý do quét lại lớp ${classCode}:`, 'Kiểm tra bài mới')?.trim(); if (!reason) return; button.disabled = true; try { await state.api.requestWritingClassScan(classCode, reason); showError('flow-error', `Đã xếp lớp ${classCode} vào hàng quét. Workflow điều phối sẽ nhận trong tối đa một phút.`); await refreshData(); } catch (error) { showError('flow-error', `Chưa quét được lớp: ${error.message}`); } finally { button.disabled = false; } }
function rememberClass(classCode) { state.recentClasses = [classCode, ...state.recentClasses.filter(item => item !== classCode)].slice(0, 8); saveClassList('writing-flow:recent-classes:v1', state.recentClasses); }
function chooseClass(classCode) { $('flow-class').value = classCode; rememberClass(classCode); void refreshData(); }
function togglePinnedClass(classCode) { state.pinnedClasses = state.pinnedClasses.includes(classCode) ? state.pinnedClasses.filter(item => item !== classCode) : [classCode, ...state.pinnedClasses].slice(0, 12); saveClassList('writing-flow:pinned-classes:v1', state.pinnedClasses); renderClasses(); }
function classCard(item, completed = false) { const classCode = item.class_code || ''; const pinned = state.pinnedClasses.includes(classCode); const card = document.createElement('article'); card.className = 'flow-class-card'; card.dataset.pinned = String(pinned); card.append(makeText('h3', classCode || item.class_name || 'Chưa rõ mã lớp'), makeText('p', item.classroom_name || item.class_name || 'Chưa có tên Classroom', 'flow-meta'), makeText('p', `Giảng viên: ${(item.teacher_names || []).join(', ') || '—'}`, 'flow-meta'), makeText('p', completed ? 'Đã hoàn thành · không quét tự động' : `Quét: ${statusNames[item.scan_status] || item.scan_status || 'chưa có'} · lần lỗi ${item.scan_attempt_count || 0}/3`, 'flow-meta'), makeText('p', `Lần quét gần nhất: ${formatTime(item.last_scan_at)}`, 'flow-meta')); if (!completed && classCode) { const actions = document.createElement('div'); actions.className = 'flow-class-card-actions'; const scan = actionButton('Quét lớp ngay', () => void requestClassScan(classCode, scan)); const show = actionButton('Xem bài lớp', () => chooseClass(classCode)); const pin = actionButton(pinned ? 'Bỏ ghim' : 'Ghim lớp', () => togglePinnedClass(classCode)); actions.append(show, scan, pin); card.append(actions); } return card; }
function orderedClasses(rows) { const rank = code => { const pinned = state.pinnedClasses.indexOf(code); if (pinned >= 0) return pinned; const recent = state.recentClasses.indexOf(code); return recent >= 0 ? 100 + recent : 1000; }; return [...rows].sort((a, b) => rank(a.class_code) - rank(b.class_code) || String(a.class_code).localeCompare(String(b.class_code), 'vi')); }
function renderClassWorkspace() { const workspace = $('flow-class-workspace'); const classCode = $('flow-class').value; workspace.hidden = state.activeView !== 'classes' || !classCode; if (workspace.hidden) return; $('flow-class-workspace-title').textContent = `Tình hình lớp ${classCode}`; const summary = $('flow-class-stage-summary'); summary.replaceChildren(); const rows = (state.counts?.stages || []).filter(row => !row.skipped); for (const stage of stages) { const count = rows.filter(row => row.stage_key === stage).reduce((total, row) => total + Number(row.pair_count || 0), 0); const card = document.createElement('article'); card.append(makeText('strong', count), makeText('span', stageNames[stage])); summary.append(card); } renderDailyBars($('flow-class-daily-chart'), state.daily, true, 120); }
function renderClasses() { const root = $('flow-classes'); root.replaceChildren(); const completed = state.activeView === 'completed_classes'; const rows = orderedClasses(completed ? state.completedClasses : state.activeClasses); if (!rows.length) root.append(makeText('p', completed ? 'Chưa có lớp đã hoàn thành.' : 'Chưa có lớp đang vận hành.', 'muted')); else for (const item of rows) root.append(classCard(item, completed)); renderClassWorkspace(); }

function renderCoverageList(rootId, limit = null) { const root = $(rootId); root.replaceChildren(); let rows = state.coverage.filter(row => !['covered', 'completed', 'excluded'].includes(row.status)); if (limit) rows = rows.slice(0, limit); if (!rows.length) return root.append(makeText('p', 'Không có lớp cần chú ý.', 'muted')); for (const item of rows) { const row = document.createElement('article'); row.className = 'flow-row'; const body = document.createElement('div'); body.append(makeText('strong', `${item.class_code || item.class_name || 'Chưa rõ lớp'} · ${coverageStatusLabels[item.status] || item.status}`), makeText('p', coverageDescription(item), 'flow-meta')); row.append(body); if (item.class_code && !['excluded', 'completed'].includes(item.status)) { const button = actionButton('Quét ngay', () => void requestClassScan(item.class_code, button)); row.append(button); } root.append(row); } }
function renderCoverage() { renderCoverageList('flow-class-coverage', 8); renderCoverageList('flow-mapping-coverage'); }
function renderAttention() { const root = $('flow-attention'); root.replaceChildren(); const rows = [...state.reviews.slice(0, 4).map(item => ({ kind: 'review', item })), ...state.issues.slice(0, 4).map(item => ({ kind: 'issue', item }))].slice(0, 8); if (!rows.length) return root.append(makeText('p', 'Không có việc cần xử lý.', 'muted')); for (const { kind, item } of rows) { const row = document.createElement('article'); row.className = 'flow-row'; const title = kind === 'review' ? `${stageNames[item.stage_key]} · lỗi sau ${item.attempt_count}/3 lần` : `Lỗi nguồn · ${sourceIssueLabel(item.reason_code)}`; row.append(makeText('div', `${title}\n${sourceName(item)} · ${item.class_code || 'ngoài lớp'}`)); root.append(row); } }

function detailButton(row, label) { return actionButton(label, () => void openDetail(row)); }
async function skipPair(pair) { const reason = prompt('Lý do bỏ qua bài này:')?.trim(); if (!reason) return; try { await state.api.skipWritingPair(pair.pair_id, reason); await refreshData(); } catch (error) { showError('flow-error', `Chưa bỏ qua được bài: ${error.message}`); } }
async function restorePair(pair) { const reason = prompt('Lý do khôi phục bài:', 'Bỏ qua nhầm')?.trim(); if (!reason) return; try { await state.api.restoreWritingPair(pair.pair_id, reason); await refreshData(); } catch (error) { showError('flow-error', `Chưa khôi phục được bài: ${error.message}`); } }
async function retryPair(pair) { const stageKey = stages.includes(state.activeView) ? state.activeView : pair.stage_key; const reason = prompt(`Lý do chạy lại từ bước “${stageNames[stageKey] || stageKey}”:`, 'Kiểm tra và chạy lại')?.trim(); if (!reason) return; try { await state.api.retryWritingPairStage(pair.pair_id, stageKey, reason); await refreshData(); } catch (error) { showError('flow-error', `Chưa tạo được lượt retry: ${error.message}`); } }
function actionCell(pair) { const cell = document.createElement('div'); cell.className = 'flow-actions'; cell.append(actionButton('Xem', () => void openDetail(pair)), actionButton('Retry', () => void retryPair(pair), 'primary'), pair.skipped_at ? actionButton('Khôi phục', () => void restorePair(pair)) : actionButton('Bỏ qua', () => void skipPair(pair))); return cell; }
function appendCell(row, content) { const cell = document.createElement('td'); if (content instanceof Node) cell.append(content); else cell.textContent = String(content ?? ''); row.append(cell); }
function renderPairs() { const head = $('flow-table-head'); const root = $('flow-pairs'); head.replaceChildren(); root.replaceChildren(); for (const key of state.visibleColumns) head.append(makeText('th', columns[key][0])); if (!state.pairs.length) { const row = document.createElement('tr'); const cell = makeText('td', 'Chưa có bài trong phạm vi đã chọn.', 'muted'); cell.colSpan = state.visibleColumns.length; row.append(cell); root.append(row); $('flow-more').hidden = true; return; } for (const pair of state.pairs) { const row = document.createElement('tr'); for (const key of state.visibleColumns) appendCell(row, columns[key][1](pair)); root.append(row); } $('flow-more').hidden = !state.nextCursor; }

function describeEvent(event) { const step = stageNames[event.stage_key] || event.stage_key || ''; if (event.kind === 'attempt') return `${step}: lần ${event.attempt_no}, ${event.status}`; if (event.kind === 'ai_call') return `${step}: gọi AI ${event.provider || ''}, ${event.status}`; if (event.kind === 'handoff') return `Chuyển ${stageNames[event.from_stage] || event.from_stage} → ${stageNames[event.to_stage] || event.to_stage}: ${event.status}`; if (event.kind === 'operator') return `Thao tác ${event.event_type}: ${event.reason || ''}`; return `${step}: ${event.status || event.kind}`; }
async function openDetail(pair) { const dialog = $('flow-detail'); const content = $('flow-detail-content'); content.textContent = 'Đang tải nội dung, Text chấm bài và log…'; dialog.showModal(); try { const [detailResponse, historyResponse] = await Promise.all([state.api.writingPairDetail(pair.pair_id), state.api.writingPairHistory(pair.pair_id)]); const detail = detailResponse.data.detail; const history = historyResponse.data.history; const grid = document.createElement('div'); grid.className = 'flow-detail-grid'; const source = document.createElement('section'); source.className = 'flow-detail-panel'; source.append(makeText('h3', 'Bài nguồn'), makeText('p', `Đề bài\n${detail.source.topic || '—'}`), makeText('p', `Ảnh biểu đồ\n${detail.source.image || '—'}`), makeText('p', `Nội dung học viên\n${detail.source.essay || '—'}`), makeText('p', `TRCC: ${detail.source.trCcCheck ? 'Có' : 'Không'}`)); const results = document.createElement('section'); results.className = 'flow-detail-panel'; results.append(makeText('h3', 'Text chấm bài')); for (const stage of detail.stages) { const block = document.createElement('details'); block.open = ['render', 'deliver'].includes(stage.stage_key); block.append(makeText('summary', `${stageNames[stage.stage_key]} · ${statusNames[stage.status] || stage.status}`), makeText('pre', stage.result ? JSON.stringify(stage.result, null, 2) : 'Chưa có kết quả.')); results.append(block); } const log = document.createElement('section'); log.className = 'flow-detail-panel flow-detail-panel-wide'; log.append(makeText('h3', 'Nhật ký và lỗi')); for (const event of history.events || []) { const line = makeText('p', `${formatTime(event.at)} · ${describeEvent(event)}${event.error_code ? ` · lỗi ${event.error_code}` : ''}`, 'flow-meta'); const workflowId = stageWorkflowIds[event.stage_key]; if (workflowId && event.n8n_execution_id) { const link = externalLink(`https://ducizone.ddns.net/workflow/${workflowId}/executions/${encodeURIComponent(event.n8n_execution_id)}`, 'Mở lượt chạy n8n', ''); line.append(' · ', link); } log.append(line); } grid.append(source, results, log); content.replaceChildren(makeText('h2', sourceName(detail.pair)), grid); } catch (error) { content.textContent = `Chưa đọc được chi tiết: ${error.message}`; } }

async function retryReview(review, button) { if (!confirm(`Chạy lại từ bước “${stageNames[review.stage_key] || review.stage_key}”?`)) return; button.disabled = true; try { await state.api.retryWritingReview(review.review_id, createRequestId()); await refreshData(); } catch (error) { showError('flow-error', `Chưa gửi được yêu cầu: ${error.message}`); button.disabled = false; } }
function renderReviews() { const root = $('flow-reviews'); root.replaceChildren(); if (!state.reviews.length) return root.append(makeText('p', 'Không có bài cần kiểm tra.', 'muted')); for (const review of state.reviews) { const row = document.createElement('article'); row.className = 'flow-row'; const body = document.createElement('div'); body.append(makeText('strong', `${stageNames[review.stage_key]} · đã thử ${review.attempt_count}/3`), makeText('p', `${sourceName(review)} · lớp ${review.class_code || 'ngoài lớp'} · lỗi ${review.error_code}`, 'flow-meta')); const button = actionButton('Chạy lại từ bước này', () => void retryReview(review, button), 'primary'); row.append(body, button); root.append(row); } }
function sourceIssueLabel(code) { return ({ FILE_TYPE_UNSUPPORTED: 'Sai loại file', FETCH_FAILED: 'Không mở được tài liệu', PARSER_FAILED: 'Không đọc được tài liệu', TOPIC_NOT_IN_REGISTRY: 'Đề không có trong kho đề', ESSAY_ANCHOR_MISSING: 'Thiếu ô “HV Viết bài”', ESSAY_CELL_MISSING: 'Thiếu ô bài làm', TEACHER_COMMENT_ANCHOR_MISSING: 'Thiếu ô “Comment của GV”', RESULT_CELL_AMBIGUOUS: 'Không xác định được ô ghi kết quả', TABLE_STRUCTURE_INVALID: 'Sai format bảng', NO_ESSAY: 'Chưa có bài làm', NOT_WRITING_DOCUMENT: 'Không phải tài liệu Writing' })[code] || code; }
async function retrySourceIssue(issue, button) { if (!confirm('Đọc lại nguồn này? Thao tác không sửa Lark Base.')) return; button.disabled = true; try { await state.api.retryWritingSourceIssue(issue.issue_key, createRequestId()); await refreshData(); } catch (error) { showError('flow-error', `Chưa đọc lại được nguồn: ${error.message}`); button.disabled = false; } }
function renderIssues() { const root = $('flow-source-issues'); root.replaceChildren(); if (!state.issues.length) return root.append(makeText('p', 'Không có lỗi nguồn.', 'muted')); for (const issue of state.issues) { const row = document.createElement('article'); row.className = 'flow-row'; const body = document.createElement('div'); body.append(makeText('strong', sourceIssueLabel(issue.reason_code)), makeText('p', `${sourceName(issue)} · lớp ${issue.class_code || 'ngoài lớp'} · bài ${issue.essay_slot || '—'}`, 'flow-meta')); const button = actionButton('Đọc lại nguồn', () => void retrySourceIssue(issue, button)); row.append(body, button); root.append(row); } }
function renderFailures() { const root = $('flow-technical-errors'); root.replaceChildren(); if (!state.failures.length) return root.append(makeText('p', 'Chưa có lỗi kỹ thuật trong bảy ngày gần đây.', 'muted')); for (const failure of state.failures) { const row = document.createElement('article'); row.className = 'flow-row'; const body = document.createElement('div'); body.append(makeText('strong', `${failure.workflow_name} · ${failure.last_node}`), makeText('p', `${formatTime(failure.last_seen_at)} · ${failure.error_kind} · gặp ${failure.seen_count || 1} lần`, 'flow-meta'), externalLink(`https://ducizone.ddns.net/workflow/${encodeURIComponent(failure.workflow_id)}`, 'Mở workflow n8n', '')); row.append(body); root.append(row); } }
const operatorLabels = { retry_requested: 'Retry bài lỗi', rerun_requested: 'Chạy lại từ một bước', skipped: 'Bỏ qua bài', restored: 'Khôi phục bài', source_edited: 'Sửa nguồn', manual_source_added: 'Thêm file ngoài lớp', class_scan_requested: 'Quét lớp ngay', legacy_imported: 'Nhập lịch sử cũ', legacy_promoted: 'Chuyển lịch sử sang nguồn mới', class_mapping_changed: 'Đổi trạng thái lớp từ mapping' };
function renderOperatorEvents() { const root = $('flow-operator-events'); root.replaceChildren(); if (!state.events.length) return root.append(makeText('p', 'Chưa có thao tác trong phạm vi đang lọc.', 'muted')); for (const event of state.events) { const row = document.createElement('article'); row.className = 'flow-row'; const body = document.createElement('div'); body.append(makeText('strong', operatorLabels[event.event_type] || event.event_type), makeText('p', `${formatTime(event.created_at)} · lớp ${event.class_code || 'ngoài lớp'} · ${event.actor_ref || 'hệ thống'}`, 'flow-meta')); if (event.reason) body.append(makeText('p', event.reason, 'flow-meta')); const states = document.createElement('details'); states.className = 'flow-audit-state'; states.append(makeText('summary', 'Xem trạng thái trước và sau'), makeText('pre', `Trước:\n${JSON.stringify(event.before_state || {}, null, 2)}\n\nSau:\n${JSON.stringify(event.after_state || {}, null, 2)}`)); body.append(states); row.append(body); root.append(row); } }
function renderLegacy() { const root = $('flow-legacy'); root.replaceChildren(); if (!state.legacy.length) return root.append(makeText('p', 'Chưa nhập lịch sử cũ trong phạm vi này.', 'muted')); for (const item of state.legacy) { const row = document.createElement('article'); row.className = 'flow-row'; row.append(makeText('div', `${item.student_name || 'Chưa có tên'} · ${item.class_code || '—'} · bài ${item.essay_slot || '—'} · ${item.source_status || '—'} · ${formatTime(item.created_at_source)}`)); root.append(row); } }
function openDailyDetails(day) { $('flow-date-from').value = day; $('flow-date-to').value = day; state.activeView = 'delivered'; state.pairs = []; state.nextCursor = null; void refreshData(); }
function renderDailyBars(root, days, interactive = true, maxHeight = 190) { root.replaceChildren(); if (!days.length) return root.append(makeText('p', 'Chưa có bài hoàn thành trong khoảng đã chọn.', 'muted')); const max = Math.max(...days.map(row => Number(row.completed_count || 0)), 1); const chart = document.createElement('div'); chart.className = 'flow-chart-bars'; for (const item of days) { const bar = document.createElement(interactive ? 'button' : 'div'); if (interactive) { bar.type = 'button'; bar.title = `Mở ${item.completed_count} bài đã giao ngày ${item.day}`; bar.addEventListener('click', () => openDailyDetails(item.day)); } bar.className = 'flow-chart-bar'; const visual = document.createElement('i'); visual.style.height = `${Math.max(3, Math.round(Number(item.completed_count || 0) / max * maxHeight))}px`; bar.append(visual, makeText('strong', item.completed_count), makeText('small', new Date(`${item.day}T00:00:00`).toLocaleDateString('vi-VN'))); chart.append(bar); } root.append(chart); }
function renderDaily() { renderDailyBars($('flow-daily-chart'), state.daily, true); }
function renderAll() { renderHeading(); renderCounts(); renderSummary(); renderCoverage(); renderAttention(); renderClasses(); renderPairs(); renderReviews(); renderIssues(); renderFailures(); renderOperatorEvents(); renderLegacy(); renderDaily(); setViewVisibility(); }

async function loadPairs(reset = true) { const cursor = reset ? {} : (state.nextCursor || {}); const response = await state.api.writingPairsPage(currentFilters({ ...pairViewFilters(), ...cursor })); const rows = response.data.pairs || []; state.pairs = reset ? rows : [...state.pairs, ...rows]; state.nextCursor = response.data.nextCursor || null; }
async function loadCommon() { const [counts, activeClasses, completedClasses] = await Promise.all([state.api.writingCounts($('flow-class').value, $('flow-teacher').value), state.api.writingClasses('active'), state.api.writingClasses('completed')]); state.counts = counts.data.counts || null; state.activeClasses = activeClasses.data.classes || []; state.completedClasses = completedClasses.data.classes || []; if (!state.filtersLoaded) { const response = await state.api.writingFilterOptions(); populateFilters(response.data.filters || {}); state.filtersLoaded = true; } }
async function loadView() { const filters = currentFilters(); if (state.activeView === 'overview') { const [coverage, reviews, issues] = await Promise.all([state.api.writingClassCoverage(), state.api.writingReviews({ ...filters, limit: 8 }), state.api.writingSourceIssues({ ...filters, limit: 8 })]); state.coverage = coverage.data.classes || []; state.reviews = reviews.data.reviews || []; state.issues = issues.data.issues || []; return; } if (state.activeView === 'mapping') { const response = await state.api.writingClassCoverage(); state.coverage = response.data.classes || []; return; } if (state.activeView === 'daily') { const response = await state.api.writingDailyStats(filters); state.daily = response.data.days || []; return; } if (state.activeView === 'classes') { if ($('flow-class').value) { const [stats] = await Promise.all([state.api.writingDailyStats(filters), loadPairs(true)]); state.daily = stats.data.days || []; } else { state.pairs = []; state.daily = []; state.nextCursor = null; } return; } if (state.activeView === 'completed_classes') return; if (state.activeView === 'review') { const response = await state.api.writingReviews({ ...filters, limit: 100 }); state.reviews = response.data.reviews || []; return; } if (state.activeView === 'source') { const response = await state.api.writingSourceIssues({ ...filters, limit: 100 }); state.issues = response.data.issues || []; return; } if (state.activeView === 'logs') { const response = await state.api.writingWorkflowFailures(0, 100); state.failures = response.data.failures || []; return; } if (state.activeView === 'audit') { const response = await state.api.writingOperatorEvents({ classCode: filters.classCode, limit: 100 }); state.events = response.data.events || []; return; } if (state.activeView === 'legacy') { const response = await state.api.writingLegacy(filters.classCode, 0, 50); state.legacy = response.data.records || []; return; } await loadPairs(true); }

async function refreshData() { clearTimeout(state.timer); if (!state.authenticated || !state.api) return; const generation = state.loginGeneration; try { await loadCommon(); await loadView(); if (generation !== state.loginGeneration) return; renderAll(); $('flow-login').hidden = true; $('flow-dashboard').hidden = false; $('flow-updated').textContent = `Đã cập nhật lúc ${new Date().toLocaleTimeString('vi-VN')}`; showError('flow-login-error'); showError('flow-error'); } catch (error) { const failure = teacherAuthFailure(error.status); if (failure) { clearLogin(); showError('flow-login-error', failure.message); globalThis.google?.accounts?.id?.disableAutoSelect?.(); return; } showError($('flow-dashboard').hidden ? 'flow-login-error' : 'flow-error', `Chưa tải được trạng thái: ${error.message}`); } state.timer = setTimeout(refreshData, 30_000); }
async function submitManual(event) { event.preventDefault(); const button = event.submitter; button.disabled = true; try { await state.api.addWritingManualSource($('flow-manual-name').value.trim(), $('flow-manual-url').value.trim(), createRequestId()); event.currentTarget.reset(); $('flow-manual-dialog').close(); showError('flow-error', 'Đã thêm file. Hệ thống sẽ kiểm đề và format trước khi chấm.'); await refreshData(); } catch (error) { showError('flow-error', `Chưa thêm được file: ${error.message}`); } finally { button.disabled = false; } }
async function handleCredential(response) { if (!response?.credential) return showError('flow-login-error', 'Không nhận được thông tin đăng nhập.'); state.loginGeneration += 1; state.authenticated = false; try { await state.sessionClient.login(response.credential); state.authenticated = true; if ($('remember-flow-login').checked) loginPreference.set(true); await refreshData(); } catch (error) { clearLogin(); showError('flow-login-error', `Không thể đăng nhập: ${error.message}`); } }
async function waitForGoogle(clientId) { for (let attempt = 0; attempt < 100; attempt += 1) { const accounts = globalThis.google?.accounts?.id; if (accounts) { accounts.initialize({ client_id: clientId, callback: handleCredential, auto_select: loginPreference.read() }); accounts.renderButton($('google-signin'), { theme: 'outline', size: 'large', text: 'signin_with', locale: 'vi' }); return; } await new Promise(resolve => setTimeout(resolve, 100)); } throw new Error('Không tải được dịch vụ đăng nhập Google.'); }
function clearLogin() { state.loginGeneration += 1; state.authenticated = false; clearTimeout(state.timer); $('flow-dashboard').hidden = true; $('flow-login').hidden = false; }
function selectView(view) { state.activeView = view; $('flow-stage-status').value = ''; state.pairs = []; state.nextCursor = null; void refreshData(); }
function clearFilters() { $('flow-search').value = ''; $('flow-class').value = ''; $('flow-teacher').value = ''; $('flow-task-type').value = ''; $('flow-stage-status').value = ''; $('flow-date-from').value = ''; $('flow-date-to').value = ''; state.pairs = []; state.nextCursor = null; void refreshData(); }
async function init() { try { const response = await fetch('./writing-flow-config.json', { cache: 'no-store' }); if (!response.ok) throw new Error('Thiếu cấu hình trang chấm bài.'); const config = await response.json(); state.sessionClient = createTeacherSessionClient({ apiBaseUrl: config.apiBase || '', sessionPath: 'api/v1/auth/session' }); state.api = createTeacherApi(config.apiBase || ''); renderColumnChoices(); $('flow-manual-form').addEventListener('submit', event => void submitManual(event)); $('flow-manual-open').addEventListener('click', () => $('flow-manual-dialog').showModal()); $('flow-detail-close').addEventListener('click', () => $('flow-detail').close()); $('flow-class').addEventListener('change', () => { if ($('flow-class').value) rememberClass($('flow-class').value); void refreshData(); }); for (const id of ['flow-teacher', 'flow-task-type', 'flow-stage-status', 'flow-date-from', 'flow-date-to']) $(id).addEventListener('change', () => void refreshData()); $('flow-search').addEventListener('input', () => { clearTimeout(state.searchTimer); state.searchTimer = setTimeout(refreshData, 350); }); for (const button of document.querySelectorAll('#flow-views [data-view]')) button.addEventListener('click', () => selectView(button.dataset.view)); $('flow-clear-filters').addEventListener('click', clearFilters); $('flow-refresh').addEventListener('click', () => void refreshData()); $('flow-more').addEventListener('click', async () => { if (!state.nextCursor || state.loadingMore) return; state.loadingMore = true; try { await loadPairs(false); renderPairs(); } finally { state.loadingMore = false; } }); const restored = await state.sessionClient.restore(); if (restored) { state.authenticated = true; await refreshData(); } await waitForGoogle(config.googleClientId); if (!state.authenticated && loginPreference.read()) globalThis.google.accounts.id.prompt(); } catch (error) { showError('flow-login-error', error.message); } }

$('remember-flow-login').checked = loginPreference.read();
$('remember-flow-login').addEventListener('change', () => { const input = $('remember-flow-login'); if (!loginPreference.set(input.checked)) input.checked = loginPreference.read(); });
$('flow-logout').addEventListener('click', () => { clearLogin(); globalThis.google?.accounts?.id?.disableAutoSelect?.(); loginPreference.set(false); $('remember-flow-login').checked = false; });
void init();
